### ISSUE TITLE
How to use multi gpus in qwen2/quantize.py?

### ISSUE THREAD

**Issue by qy1026** [Tlntin/Qwen-TensorRT-LLM#105]
Single gpu(48GB) can't support qwen1.5-72B-awq-int4 to be converted to .pt format, which will trigger an OOM error. How can I use multi gpus in qwen2/quantize.py?

**Comment by Tlntin** [comment]
unmark the line 113 and 114 may work it.
[link](https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen2/quantize.py#L113)

**Comment by Tlntin** [comment]
already fix
