### ISSUE TITLE
qwen1.5 编译错误：KeyError: 'kv_cache_block_pointers_list'

### ISSUE THREAD

**Issue by whk6688** [Tlntin/Qwen-TensorRT-LLM#107]
python build.py --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --hf_model_dir /home/www/.cache/huggingface/hub/models--Qwen--Qwen1.5-7B-Chat-GPTQ-Int4/snapshots/9f8cfb07be2cae79313f781ac5d174361ae42f6f \
                --quant_ckpt_path /home/www/.cache/huggingface/hub/models--Qwen--Qwen1.5-7B-Chat-GPTQ-Int4/snapshots/9f8cfb07be2cae79313f781ac5d174361ae42f6f

![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/17873056/44a0f057-ae81-401b-a5fc-1590dbd01ef4)

**Comment by Tlntin** [comment]
tensorrt-llm版本？

**Comment by whk6688** [comment]
Qwen-TensorRT-LLM  这个项目里的 Qwen1.5
