### ISSUE TITLE
想请教一下qwen1.5_7b和llama系的区别

### ISSUE THREAD

**Issue by DBCGary** [Tlntin/Qwen-TensorRT-LLM#108]
我个人感觉两个模型差不多，我在官方trt-llm中尝试用llama的代码去构建qwen1.5_7b，虽然没报错，但可以看到推理结果不正确，想请教下大佬有什么区别吗

**Comment by Tlntin** [comment]
结构上来说qwen1.5确实和llama2没啥区别，可能就网络层名称，rope base，qkv.bais不一样咯。
