### ISSUE TITLE
Hi, a error about kv_cache_block_pointers_list

### ISSUE THREAD

**Issue by lll143653** [Tlntin/Qwen-TensorRT-LLM#109]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/58139948/6cdcd432-6d3f-4804-a801-689b99773c1b)
just like this, with qwen1.5 0.5b chat

**Comment by Tlntin** [comment]
only support TensorRT-LLM 0.8.0, not 0.9.0

**Comment by lll143653** [comment]
ok
