### ISSUE TITLE
请教一个codeqwen7b模型build过程的一个问题

### ISSUE THREAD

**Issue by shiqingzhangCSU** [Tlntin/Qwen-TensorRT-LLM#111]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/44834482/0b654a5d-8771-4d70-8fc6-d5189c5d663e)

这里会引发断言错误，为啥这里要加一个断言呢？

**Comment by Tlntin** [comment]
可以注释。

**Comment by Tlntin** [comment]
应该GQA（分组注意力）的老代码了，晚点看看。
