### ISSUE TITLE
qwen1.5进行解码的时候，部分汉字出现�问题，然后跟后面一个token连起来一起解码，结果就正常了，怎么处理

### ISSUE THREAD

**Issue by MuyeMikeZhang** [Tlntin/Qwen-TensorRT-LLM#115]
比如[23433]，[43720]分开解码结果分别是�，合在一起就可以正常解码，应该是强行分开导致的错误

**Comment by Tlntin** [comment]
每次解码后检测一下是否乱码，如果乱码那就不解码，等待下次拼接。
参考代码：https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen2/run_old.py#L273
