### ISSUE TITLE
能支持qwen-vl吗？

### ISSUE THREAD

**Issue by tms2003** [Tlntin/Qwen-TensorRT-LLM#21]
多模态才是未来啊。能支持否？

**Comment by Tlntin** [comment]
暂时无相关计划

**Comment by jkl375** [comment]
> 多模态才是未来啊。能支持否？
可以把文本模型和视觉模型分别转出来，然后拼起来

**Comment by zhaohb** [comment]
最新消息说nv已经在支持qwen-vl了，就看什么时候release了

**Comment by zhaohb** [comment]
已经支持了，目前visul支持fp16， llm模型支持fp16、weight only int8/int4，可以测试下
