### ISSUE TITLE
请问如何支持 qwen-14b-chat-int4 

### ISSUE THREAD

**Issue by Nisoka** [Tlntin/Qwen-TensorRT-LLM#33]
qwen-14b-chat-int4 的模型 是否可以类似 qwen-7b-chat 一样的流程执行呢，int4 需要build.py 时候特殊处理么 谢谢

**Comment by Tlntin** [comment]
不支持，请从qwen-14b-chat来量化。
用int4 weight only或者gptq.

**Comment by Tlntin** [comment]
qwen-14b-chat-int4本质上等于wen-14b-chat + auto-gptq

**Comment by Tlntin** [comment]
现在支持直接导入官方int4权重了，相关[commit](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/commit/d8e85043b170227a3c05f670fa06bd98f5060a01)
