### ISSUE TITLE
长序列（>2048)出现output为空

### ISSUE THREAD

**Issue by YiqiangLi** [Tlntin/Qwen-TensorRT-LLM#39]
现象和这个描述很相似，但默认已经用了gpt attention pluginde rope, 会是什么问题呢？

//////////////////////////
完整支持原版的logn和ntk（这俩参数是用于增强模型长输入的生成效果，这里的长输入指的是输入长度大于2048小于8192）。不过由于trt-llm的某些bug，导致输入长度>2048时，实际输出会很短甚至为空，详见https://github.com/NVIDIA/trt-samples-for-hackathon-cn/issues/90，加上rope放gpt attention plugin里面计算更快，所以我们logn注释掉了。

**Comment by Tlntin** [comment]
logn+ntk相关代码还未完美支持，暂时注释掉了，所以长序列就是会为空。

**Comment by Tlntin** [comment]
补充一下：NTK目前只在输入长度>seq_length的时候才生效。
如果你用的是qwen 7b 1.1这种，可以将`qwen/default_config.py`里面的2048设置成8192，这样就不需要NTK和logn来线性插值了。

**Comment by YiqiangLi** [comment]
是的，但我们目前用的是14B。。

**Comment by Tlntin** [comment]
好的，最近我会尝试恢复注释的代码。

**Comment by Tlntin** [comment]
已修复。
本机测试了1.8b/7b 的10k输入，以及14b的4k输入（显卡限制，非模型极限），均正常了。
相关commit: https://github.com/Tlntin/Qwen-TensorRT-LLM/commit/89e3dc417f22fdfd586dd10f9b85c0f16962cc5f
注：启用danamic_ntk后，1.8b/7b最大可以开启32k输入，14b最大应该是8k。
