### ISSUE TITLE
AWQ现在还不支持张量并行吗？tp_size=4，不成功

### ISSUE THREAD

**Issue by Coder-nlper** [Tlntin/Qwen-TensorRT-LLM#40]
GPTQ量化，4卡张量并行返回结果也是错误的，是不是也不支持呢？

**Comment by Coder-nlper** [comment]
感谢大佬的工作！试了下单卡AWQ量化Qwen7B，生成速度达到89 tokens /s，效果非常6！！！

**Comment by Tlntin** [comment]
awq多卡已修复，相关commit https://github.com/Tlntin/Qwen-TensorRT-LLM/commit/6b612128d7eed70f9a6ca69a860c7e63c35119aa

**Comment by Tlntin** [comment]
gptq我也看一下，估计是权重分割的问题

**Comment by Tlntin** [comment]
gptq多卡乱码问题已修复。
相关commit https://github.com/Tlntin/Qwen-TensorRT-LLM/commit/e262c127a6195c376b80f46dbdf5dba0ad9cfc1b
附成功截图：
![4gvPMprCEj](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/26670f00-6d79-4937-96ff-d15e6dfe687c)
