### ISSUE TITLE
运行build的时候出了点问题

### ISSUE THREAD

**Issue by qiezikuangge** [Tlntin/Qwen-TensorRT-LLM#42]
```
from tensorrt_llm.models import (
ImportError: cannot import name 'weight_only_groupwise_quantize' from 'tensorrt_llm.models' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/__init__.py)
```
我的tensorrt-llm是0.6.0的

**Comment by Tlntin** [comment]
本仓库还未支持0.6.0/0.6.1，急用可以看这个仓库的里面examples/qwen代码：https://github.com/Tlntin/TensorRT-LLM

**Comment by Tlntin** [comment]
已升级0.6.1，可以再试试了！

**Comment by qiezikuangge** [comment]
感谢，另外再请教个问题，这里加载fp16模型的时候为什么不load到gpu上呢
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/50002441/e13a1fbf-77bc-46b8-99ed-0ccbb0b455ea)

**Comment by Tlntin** [comment]
这里如果加载到gpu里面，待会TensorRT-LLM编译Engine的时候显存就不够用了😅，相当于一个模型两份显存，一份在pytorch，一份在TensorRT-LLM中。
