### ISSUE TITLE
Qwen-72B有遇到输入超过2048以后返回有问题的情况吗

### ISSUE THREAD

**Issue by piaoxiaobo** [Tlntin/Qwen-TensorRT-LLM#45]
Qwen-72B有遇到输入超过2048以后返回有问题的情况吗

**Comment by Tlntin** [comment]
建议修改：
1. 修改[defualt_config.py](https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen/default_config.py#L32)的`seq_length`为32768，当然，这里也建议把max_input_len = 2048和max_new_tokens = 2048改成seq_length的长度。
2. 修改[build.py](https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen/build.py#L199)的`rotary_base`为1000000

以上两个参数的数值来自模型内置的[config.json](https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/config.json)
后续我会增加代码来自动提醒用户（指开发者）来修正对应的参数。

**Comment by nanmi** [comment]
您好，我也遇到同样的错误，按照您提供的建议修改后输出依然是special token id，还有其他的可能的经验可以分享吗 :)

**Comment by Tlntin** [comment]
> 您好，我也遇到同样的错误，按照您提供的建议修改后输出依然是special token id，还有其他的可能的经验可以分享吗 :)

是指所有输出都是`special token id`吗？

**Comment by nanmi** [comment]
> > 您好，我也遇到同样的错误，按照您提供的建议修改后输出依然是special token id，还有其他的可能的经验可以分享吗 :)
> 
> 是指所有输出都是`special token id`吗？

是的输出几乎全部是`<|im_start|>` `<|im_end|>`

**Comment by Tlntin** [comment]
好的，那可能和这个一样了，需要加ntk和logn
https://github.com/Tlntin/Qwen-TensorRT-LLM/issues/39

**Comment by piaoxiaobo** [comment]
有遇到输入11k之后就报错的问题吗？输入11k以下就不会报错
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/34496544/e9a0763a-7372-4dca-9bc0-171f33e011d1)

**Comment by Tlntin** [comment]
> 有遇到输入11k之后就报错的问题吗？输入11k以下就不会报错 ![image](https://private-user-images.githubusercontent.com/34496544/290709801-e9a0763a-7372-4dca-9bc0-171f33e011d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg1MTEsIm5iZiI6MTcwMjYwODIxMSwicGF0aCI6Ii8zNDQ5NjU0NC8yOTA3MDk4MDEtZTlhMDc2M2EtNzM3Mi00ZGNhLTliYzAtMTcxZjMzZTAxMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTE3Y2UxODllZmYwNjI2MTkyMTBjN2RjMDJhMmNlYTg3MDM2YWFkMDc0ZTBmZGFjODc3MTQ2N2U0MTExZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jipotRbsw2dwfF6Q-Py05zNA1_cGyQxl4cMZQvxojQ0)

这？有rust的东西？

**Comment by Tlntin** [comment]
我刚刚本机测了一下1.8b的，6k输入，2k输出。
随便网上找了两篇作文，凑了5-6k左右的输入，然后输出是正常的。
注：最新代码已经会自动读取seq_length和rotary_emb_base参数了，按理可以原生支持input_length < seq_length的推理，不需要ntk(ntk只有在input_length > seq_length时才生效)
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/ced0d2a7-30fe-4810-b2a9-14a6c83a57e2)
附成功截图
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/a1dbd5d4-ebf1-41f1-a74d-5828b1f488b6)
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/9ba1be12-3453-492f-9a97-62ce77fa9a71)

**Comment by Tlntin** [comment]
这个问题应该和ntk无关，是由于`rotary_base没有设置对导致的`，稍后我会重新上传一个代码。

**Comment by lyc728** [comment]
> rotary_base

这个代码能兼容0.5.0的分支吗？

**Comment by lyc728** [comment]
> 1000000

7b的模型需要怎么修改呢？

**Comment by Tlntin** [comment]
> > 1000000
> 
> 7b的模型需要怎么修改呢？

7b 1.1应该不需要改。1.0需要ntk后续支持。具体可以看seq_length, 2048的是1.0版。

**Comment by lyc728** [comment]
> 应该不需要改

好的 意思是我1.1版本，在你的版本0.5.0中 代码参数也不用修改是吧  输入为小于6K，解析结果不会乱码是吧

**Comment by Tlntin** [comment]
> > 应该不需要改
> 
> 好的 意思是我1.1版本，在你的版本0.5.0中 代码参数也不用修改是吧 输入为小于6K，解析结果不会乱码是吧

是的，你可以去试试。

**Comment by lyc728** [comment]
> > > 应该不需要改
> > 
> > 
> > 好的 意思是我1.1版本，在你的版本0.5.0中 代码参数也不用修改是吧 输入为小于6K，解析结果不会乱码是吧
> 
> 是的，你可以去试试。

不行啊，我这边看推出来还是有问题 
python3 tools/inflight_batcher_llm/end_to_end_streaming_client.py -p "介绍潮汕元旦可以游玩的地方"  -o 100

介绍潮汕元旦可以游玩的地方，希望对大家有所帮助。<|endoftext|>（1）写出图中字母所代表的地理事物名称：A______，B______．
（2）图中①②③④⑤⑥⑦⑧⑨⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩�

**Comment by Tlntin** [comment]
> > > > 应该不需要改
> > > 
> > > 
> > > 好的 意思是我1.1版本，在你的版本0.5.0中 代码参数也不用修改是吧 输入为小于6K，解析结果不会乱码是吧
> > 
> > 
> > 是的，你可以去试试。
> 
> 不行啊，我这边看推出来还是有问题 python3 tools/inflight_batcher_llm/end_to_end_streaming_client.py -p "介绍潮汕元旦可以游玩的地方" -o 100
> 
> 介绍潮汕元旦可以游玩的地方，希望对大家有所帮助。<|endoftext|>（1）写出图中字母所代表的地理事物名称：A______，B______． （2）图中①②③④⑤⑥⑦⑧⑨⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩⑩�

default_config.py里面的seq_length换成8192

**Comment by lyc728** [comment]
我这边改了序列长度，因为有的输入大于2048，我的max_input_len改成6144，现在输出同上面一样，也是乱序的

**Comment by Tlntin** [comment]
> 我这边改了序列长度，因为有的输入大于2048，我的max_input_len改成6144，现在输出同上面一样，也是乱序的

好的，晚点我测试一下。

**Comment by lyc728** [comment]
> > 我这边改了序列长度，因为有的输入大于2048，我的max_input_len改成6144，现在输出同上面一样，也是乱序的
> 
> 好的，晚点我测试一下。

现在我短文本是可以的，超过上千的字符是乱序生成

**Comment by Tlntin** [comment]
> > > 我这边改了序列长度，因为有的输入大于2048，我的max_input_len改成6144，现在输出同上面一样，也是乱序的
> > 
> > 
> > 好的，晚点我测试一下。
> 
> 现在我短文本是可以的，超过上千的字符是乱序生成

看了你一下你之前的言论，你貌似是用triton部署的，并且没有构造chat需要的输入？
我本机测试了一下7b-chat,输入长度5k左右（让他总结两篇作文），启动用的是本机的api.py和web_demo.py，输出结果是正常的。

**Comment by lyc728** [comment]
我是用triton去启动的，前面也没有构造需要的chat 这个有影响吗？










 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年12月22日(周五) 晚上7:26写道:

  

    
我这边改了序列长度，因为有的输入大于2048，我的max_input_len改成6144，现在输出同上面一样，也是乱序的
  
好的，晚点我测试一下。
  
现在我短文本是可以的，超过上千的字符是乱序生成
  
看了你一下你之前的言论，你貌似是用triton部署的，并且没有构造chat需要的输入？
 我本机测试了一下7b-chat,输入长度5k左右（让他总结两篇作文），启动用的是本机的api.py和web_demo.py，输出结果是正常的。

**Comment by Tlntin** [comment]
> 我是用triton去启动的，前面也没有构造需要的chat 这个有影响吗？
> […](#)
> ----------回复的邮件信息---------- ***@***.***&gt; 于2023年12月22日(周五) 晚上7:26写道: 我这边改了序列长度，因为有的输入大于2048，我的max_input_len改成6144，现在输出同上面一样，也是乱序的 好的，晚点我测试一下。 现在我短文本是可以的，超过上千的字符是乱序生成 看了你一下你之前的言论，你貌似是用triton部署的，并且没有构造chat需要的输入？ 我本机测试了一下7b-chat,输入长度5k左右（让他总结两篇作文），启动用的是本机的api.py和web_demo.py，输出结果是正常的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

有影响，chat模型一般需要构造prompt,不能直接输入文本，否则会导致胡说八道，也就是类似乱码的情况，如何构造prompt可以去debug一下原版的模型，或者看一下本项目的配套视频。

**Comment by lyc728** [comment]
那我得短文本也是没有构造prompt，它却能正常输出

**Comment by ywx217** [comment]
我之前使用的是TensorRT-LLM v0.7.1 官方提供的 example 转换 72B 模型，也遇到了同样的问题。
改成用这个仓库提供的脚本后，问题解决。

感谢作者！
