### ISSUE TITLE
qwen-14b-chat-int4转完之后推理乱码

### ISSUE THREAD

**Issue by xiamaozi11** [Tlntin/Qwen-TensorRT-LLM#47]
Loading engine from /app/trt_engines/fp16/1-gpu/Qwen-14B-Chat-Int4_float16_tp1_rank0.engine
Input: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
你好，请问你叫什么？<|im_end|>
<|im_start|>assistant
"
Output: "odos或多扫玩操的最后一操.hd荟ulas Schwe螺丝ass服务平台的日子onde的各项插督 unh操=msgitousRaw鄢操才行irth妩诗鄢绿中心城市挂=color诊所荟或多或多立马署缫玩尚 slip的效果ations鄢映绿色令牌чество挂的优点 Uma白天耍uner_detectoronde绿挂蓦五六大事 Loapo天使操亲切赖以Q upside合适 Bren挂挂 }];

操或多挂де-fw首位或多���挂挂挂挂挂逐走势图挂 peoplecontin舔放射 +/-操蓦挂挂中途挂操大户acs挂 ±挂挂 Lunar的心-fw挂olly挂心得操操挂挂さ Serv操挂操苕已然挂操挂操操enido令牌鄢зон双赢的心操挂 Daughter亲切打造成挂蓦挂挂操翎onde挂挂绿 multic天使操ilater走势图чество挂 hanging天使挂操苌挂首选挂开业操旅游局挂_yaml当前位置挂和平 slam挂 Lon操挂钟挂ations挂把自己的挂的效果的缘钟挂per挂挂挂牌亲切"

**Comment by xiamaozi11** [comment]
a100上推理的

**Comment by Tlntin** [comment]
使用gptq那个命令编译的吗

**Comment by xiamaozi11** [comment]
transformers版本问题。4.35.0就ok了
