### ISSUE TITLE
cnn_dailymail

### ISSUE THREAD

**Issue by lyc728** [Tlntin/Qwen-TensorRT-LLM#49]
你好，为什么下载下来的模型需要运行这个脚本python3 hf_qwen_convert.py  然而加载脚本会去加载这个数据集，而下载下来也一直加载不进去，请解答一下，谢谢诶！

**Comment by Tlntin** [comment]
这个数据集会用于int8量化标定，以及 summeriye.py需要它做评测。
下载不了可以看看readme，有提供百度网盘下载。

**Comment by lyc728** [comment]
博主 又遇到过服务启动成功，但是进行调用出错吗？

**Comment by lyc728** [comment]
> 这个数据集会用于int8量化标定，以及 summeriye.py需要它做评测。 下载不了可以看看readme，有提供百度网盘下载。
我已经下载完了这个数据 ，但是load_dataset一直有问题

**Comment by Tlntin** [comment]
> 博主 又遇到过服务启动成功，但是进行调用出错吗？ "error":"Traceback (most recent call last):\n File "/models/liuyuanchao/tensorrtllm_backend/triton_model_repo/tensorrt_llm_bls/1/model.py", line 323, in execute\n raise pb_utils.TritonModelException(\nc_python_backend_utils.TritonModelException: Model postprocessing - Error when running inference: [request id: <id_unknown>] expected 4 inputs but got 1 inputs for model 'postprocessing'\n"}

目前triton这里只支持本项目的release 0.5.0，并且需要使用配套的trtion 23.10版本的镜像，具体可以先切本项目分支到release 0.5.0，再详细看readme。

**Comment by lyc728** [comment]
> > 博主 又遇到过服务启动成功，但是进行调用出错吗？ "error":"Traceback (most recent call last):\n File "/models/liuyuanchao/tensorrtllm_backend/triton_model_repo/tensorrt_llm_bls/1/model.py", line 323, in execute\n raise pb_utils.TritonModelException(\nc_python_backend_utils.TritonModelException: Model postprocessing - Error when running inference: [request id: <id_unknown>] expected 4 inputs but got 1 inputs for model 'postprocessing'\n"}
> 
> 目前triton这里只支持本项目的release 0.5.0分支，并且需要使用配套的trtion 23.10版本的镜像，具体可以先切本项目分支到release 0.5.0，再详细看readme。

我镜像使用的nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3 23.10同时triton_trt_llm  也是0.5，跟着一个博主操作来的，结果测试就没结果

**Comment by Tlntin** [comment]
可能安装TensorRT-LLM这里出了问题，之前TensorRT-LLM默认是0.5.0分支，现在默认是main(开发）分支，所以这里安装的是很需要手动设置为0.5.0去安装。
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/13c2164f-fcda-4ee1-863a-723d2bdbeabb)

**Comment by lyc728** [comment]
> 可能安装TensorRT-LLM这里出了问题，之前TensorRT-LLM默认是0.5.0分支，现在默认是main(开发）分支，所以这里安装的是很需要手动设置为0.5.0去安装。 ![image](https://private-user-images.githubusercontent.com/28218658/291307405-13c2164f-fcda-4ee1-863a-723d2bdbeabb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzAxODIsIm5iZiI6MTcwMjk2OTg4MiwicGF0aCI6Ii8yODIxODY1OC8yOTEzMDc0MDUtMTNjMjE2NGYtZmNkYS00ZWUxLTg2M2EtNzIzZDJiZGJlYWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYzMyMjdhNjhmZWFlODM1YjEwZjg1NjY3NzRlYjYwNjM3ZDFhZTcwNTllZTRjMGU1MDdmM2NmOTY1MTQ3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xerpwygsz1fQKX8z6oKg1Arfpz_pYXOdzWcr1kiIRw4)

博主我发现你构建TRT模型版本不一致

**Comment by lyc728** [comment]
> > 博主我发现你构建TRT模型版本不一致
> 
> 哦？你弄错版本了吧

首先我转模型一个容器，另外一个进行启动服务，然后看出来TRT版本不一致

**Comment by Tlntin** [comment]
> 首先我转模型一个容器，另外一个进行启动服务，然后看出来TRT版本不一致

难怪，还是建议同一个容器。

**Comment by lyc728** [comment]
tritonserver --model-repository=/models 前面用这个启动服务 能看出来前处理还是模型构建问题 这个什么都看不出来

**Comment by Tlntin** [comment]
mpi库的问题。
建议统一用0.5.0分支，如果要用triton部署的话，0.6.1的估计还要再等等。

**Comment by lyc728** [comment]
我是用的0.5 我看的你得博客操作的  mpi库有什么解决办法吗

**Comment by Tlntin** [comment]
> 我是用的0.5 我看的你得博客操作的 mpi库有什么解决办法吗

mpi库我在AutoDL上面手动编译的时候遇到过，最后解决办法使用conda安装的mpi。
你如果需要可以参考该帖，手动编译一波容器？
https://zhuanlan.zhihu.com/p/663915644

**Comment by lyc728** [comment]
> > 我是用的0.5 我看的你得博客操作的 mpi库有什么解决办法吗
> 
> mpi库问题我在AutoDL上面手动编译的时候遇到过，最后解决办法使用conda安装的mpi。 你如果需要可以参考该帖，手动编译一波容器？ https://zhuanlan.zhihu.com/p/663915644

博主，再请教下 我这边按照你的教程，首先创建了一个容器，后面不是还要转TRT吗？这边我看到你还是重新构建了容器，这边不不是一致的吧？
<img width="495" alt="企业微信截图_17029764412942" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/e0bbc458-5b87-417e-bcea-f7803228544d">

**Comment by Tlntin** [comment]
> > > 我是用的0.5 我看的你得博客操作的 mpi库有什么解决办法吗
> > 
> > 
> > mpi库问题我在AutoDL上面手动编译的时候遇到过，最后解决办法使用conda安装的mpi。 你如果需要可以参考该帖，手动编译一波容器？ https://zhuanlan.zhihu.com/p/663915644
> 
> 博主，再请教下 我这边按照你的教程，首先创建了一个容器，后面不是还要转TRT吗？这边我看到你还是重新构建了容器，这边不不是一致的吧？ <img alt="企业微信截图_17029764412942" width="495" src="https://private-user-images.githubusercontent.com/88084847/291533289-e0bbc458-5b87-417e-bcea-f7803228544d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzY5MzAsIm5iZiI6MTcwMjk3NjYzMCwicGF0aCI6Ii84ODA4NDg0Ny8yOTE1MzMyODktZTBiYmM0NTgtNWI4Ny00MTdlLWJjZWEtZjc4MDMyMjg1NDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA5MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjU2YWNjNjI3OTE3YmMwYzczYzU0ZjhmY2NmMTE3MmYxMzdlN2QyZmVjYzI0ZDQ4ODVjZTI1NTU2ZjAwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x7llIxBiq8BpURPHGnfsMHnLHiSkO4nlxPOxvaHJ7UY">
> 博主，再请教下 我这边按照你的教程，首先创建了一个容器，后面不是还要转TRT吗？
是的
> 这边我看到你还是重新构建了容器，这边不是一致的吧？
不明白啥意思？triton的容器和普通trt-llm容器有些差异，triton的容器主要是部署，trt-llm容器用于测试和开发。所以一般先跑通trt-llm的容器，再去用triton的容器。我感觉你可能顺序搞反了。

**Comment by lyc728** [comment]
我是搞部署的，这边我理解triton的容器的TRT环境应该和trt-llm的容器环境保持一致把，但是我看到你这边下载的环境并没有一致

**Comment by Tlntin** [comment]
> 我是搞部署的，这边我理解triton的容器的TRT环境应该和trt-llm的容器环境保持一致把，但是我看到你这边下载的环境并没有一致

下面这俩是配套的，上面的部署教程也是基于release/0.5.0写的，目前0.6.1还没有官方triton容器
https://github.com/Tlntin/Qwen-TensorRT-LLM/tree/release/0.5.0
docker pull nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3
readme最前面也写清楚了
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/f9b91d80-0c50-49e6-876e-d0cc54b1b354)

**Comment by lyc728** [comment]
好吧  我是直接拉你的镜像去建立的环境 我再拉一下代码 感谢

**Comment by lyc728** [comment]
大佬你好，麻烦再问下，如何在triton中的nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3 这个环境中添加backend torch模型和onnx，因为这个环境中只有llm的环境，
<img width="706" alt="企业微信截图_170304134761" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/c141a501-0039-4191-8b3f-e1b5ae269933">

**Comment by Tlntin** [comment]
这？我没试过。
手动编译一波需要的库进去？
https://github.com/triton-inference-server/python_backend
https://github.com/triton-inference-server/onnxruntime_backend

**Comment by lyc728** [comment]
大佬，你好，现在我把max_input_len 改为8000，我的两站40G加载不进去了，这边我想问下有什么办法还能减少显存的办法，我是采用的第一张图，转成TRT, 还想问下后面的gptq有什么不同吗？哪一个显存占用更少呢？
<img width="400" alt="企业微信截图_17031381653518" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/1436a267-15be-4b53-92d4-7dc1f4bbc94e">
<img width="464" alt="企业微信截图_17031381364959" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/35102486-6dea-4e29-b4da-71ba90c79edb">

**Comment by Tlntin** [comment]
> 大佬，你好，现在我把max_input_len 改为8000，我的两站40G加载不进去了，这边我想问下有什么办法还能减少显存的办法，我是采用的第一张图，转成TRT, 还想问下后面的gptq有什么不同吗？哪一个显存占用更少呢？ <img alt="企业微信截图_17031381653518" width="400" src="https://private-user-images.githubusercontent.com/88084847/292106714-1436a267-15be-4b53-92d4-7dc1f4bbc94e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzg5NzAsIm5iZiI6MTcwMzEzODY3MCwicGF0aCI6Ii84ODA4NDg0Ny8yOTIxMDY3MTQtMTQzNmEyNjctMTViZS00YjUzLTkyZDQtN2RjMWY0YmJjOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA2MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNTY0NjJiY2E1MGNiMDBmYjE2YWY3ZGI0ZDM1NmI5ZGUwODc5NTA0NGI2OWI0NGRkMmM0ZjliMTgzYzA4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WM6f3rq5kXkMWgkZPpMLaZsmyr085VDpVFZIj3WeAO0"> <img alt="企业微信截图_17031381364959" width="464" src="https://private-user-images.githubusercontent.com/88084847/292106812-35102486-6dea-4e29-b4da-71ba90c79edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzg5NzAsIm5iZiI6MTcwMzEzODY3MCwicGF0aCI6Ii84ODA4NDg0Ny8yOTIxMDY4MTItMzUxMDI0ODYtNmRlYS00ZTI5LWI0ZGEtNzFiYTkwYzc5ZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA2MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYWQ4MmMyYjdlZDdkZDE4OWZmZTQ4YzhjNzdmZDgxNThhODA0MDJmZjc5ZWM5MjFhM2Y2NThlN2I5YThiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7dQqQjF-ILI46dLA84E0fln5uEjMrh1abm0n32Pm-30">

两者显存占用差不多，下面的效果会好一些。

**Comment by lyc728** [comment]
> 8000

还有一个问题是，我转TRT的脚本如下
python build.py --hf_model_dir ./tmp/Qwen/7B/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4 \
                --output_dir ./tmp/Qwen/7B/trt_engines/int4_weight_only/1-gpu/
在代码参数中将max_input_len 改为8000后，其它均未改变，现在输出的结果是乱序输出，没有一定的逻辑，这边还有其它参数需要改的吗？

**Comment by Tlntin** [comment]
> > 8000
> 
> 还有一个问题是，我转TRT的脚本如下 python build.py --hf_model_dir ./tmp/Qwen/7B/ --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4 --output_dir ./tmp/Qwen/7B/trt_engines/int4_weight_only/1-gpu/ 在代码参数中将max_input_len 改为8000后，其它均未改变，现在输出的结果是乱序输出，没有一定的逻辑，这边还有其它参数需要改的吗？

这个是老问题了，输入超过seq_length(8192)会乱码，目前建议是6k左右输入，留2k做输出会比较好。

**Comment by lyc728** [comment]
大佬现在这个还有办法解决嘛？

**Comment by Tlntin** [comment]
> 大佬现在这个还有办法解决嘛？

最近两天在看，不一定能解决，还在测试。

**Comment by lyc728** [comment]
现在我们测试发现输入为4096的长度，输出是2048，转TRT部分脚本如下
python build.py --hf_model_dir ./tmp/Qwen/7B/
--dtype float16
--remove_input_padding
--use_gpt_attention_plugin float16
--use_gemm_plugin float16
--use_weight_only
--weight_only_precision int4
--output_dir ./tmp/Qwen/7B/trt_engines/int4_weight_only/1-gpu/
没有使用其它脚本 只用了build这个，发现结果也是乱序的，模型是72B的

**Comment by Tlntin** [comment]
> 现在我们测试发现输入为4096的长度，输出是2048，转TRT部分脚本如下 python build.py --hf_model_dir ./tmp/Qwen/7B/ --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4 --output_dir ./tmp/Qwen/7B/trt_engines/int4_weight_only/1-gpu/ 没有使用其它脚本 只用了build这个，发现结果也是乱序的，模型是72B的

额，那就可能是哪个参数没设置对导致的。
目前没有能跑72b的卡，所以测试不了，目前你这个issue暂时先关闭了，你遇到的情况和下面的是一样的，后续关注下面的issue吧
https://github.com/Tlntin/Qwen-TensorRT-LLM/issues/45
