### ISSUE TITLE
想使用baichuan2部署api的话该修改什么地方适配百川模型呢？

### ISSUE THREAD

**Issue by secain** [Tlntin/Qwen-TensorRT-LLM#52]
已经使用tensorrt-llm 0.6.1转换了baichuan2模型并成功运行，现在想部署一个api

**Comment by Tlntin** [comment]
triton吗？还是api.py呢

**Comment by secain** [comment]
> triton吗？还是api.py呢
现在只要api.py 。triton之后也需要用到

**Comment by Tlntin** [comment]
debug一下你就知道，主要是改run.py
