### ISSUE TITLE
Use official int4 weights, e.g. Qwen-1_8B-Chat-Int4 model(recommended) -  Build TRT-LLM engine

### ISSUE THREAD

**Issue by byjswr** [Tlntin/Qwen-TensorRT-LLM#53]
请问使用样例指令
python build.py --hf_model_dir Qwen-1_8B-Chat-Int4 \
                --quant_ckpt_path Qwen-1_8B-Chat-Int4 \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --world_size 1 \
                --tp_size 1 \
                --output_dir ./tmp/Qwen/1.8B/trt_engines/int4-gptq/1-gpu
 一直卡在
<img width="741" alt="企业微信截图_1703647252769" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/53067559/bea0f1b2-e765-46fe-9d89-c348a5414adf">正常吗

**Comment by Tlntin** [comment]
你可以试试0.5.0分支，main还没测试完（昨天升的0.7.0，0.6.0忘记tag了）

**Comment by lyc728** [comment]
> mp/Qwen/1.8B/trt_engines/int4-gptq/1-g



> 试试
你好 我用0.5.0分支 去构建int4-gptq的时候，进行build 会报错
<img width="464" alt="企业微信截图_17036585442620" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/ed965ea7-148c-4c81-91c9-c6f51a01f2ff">

<img width="739" alt="企业微信截图_17036583384862" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/37ab58a1-a31e-4740-a3d5-614b06fe2cb9">

**Comment by Tlntin** [comment]
会不会是你的int4权重下载的有问题？

**Comment by lyc728** [comment]
> 会不会是你的int4权重下载的有问题？

构建其它环境就可以

**Comment by Tlntin** [comment]
好的，我明天试试。

**Comment by Tlntin** [comment]
测试了main分支的1.8b/7b/14b的int4权重导入均正常，可能你需要检查一下你的模型权重。
