### ISSUE TITLE
使用autodl编译tensorrt-llm有问题

### ISSUE THREAD

**Issue by oreo-lp** [Tlntin/Qwen-TensorRT-LLM#54]
您好，看过您的b站（已三连）和博文，也使用autodl进行tensorrt-llm进行编译，但是每次编译到100%的时候（编译没有结束，没有生成build文件夹，没有tensorrt-llm.whl文件），服务器总是会断开。而且我发现服务器的系统盘在编译的时候会骤增，每次编译都会到80%左右（我也已经export TMPDIR=/root/autodl-tmp了），为什么系统盘会骤增，服务器断开是不是这个原因？

**Comment by Tlntin** [comment]
可能是cpu不太行？或者内存不够？应该至少要40G以上。

**Comment by oreo-lp** [comment]
我看生成的/tmp/tmpxft_00001863_00000000-9_bf16_int4_gemm_fg_scalebias.compute_80.ptx这些中间文件，都是放在\tmp系统盘中的，大佬知道这些数据是啥时候产生的吗？如何放到数据盘吗？

**Comment by oreo-lp** [comment]
> 我看生成的/tmp/tmpxft_00001863_00000000-9_bf16_int4_gemm_fg_scalebias.compute_80.ptx这些中间文件，都是放在\tmp系统盘中的，大佬知道这些数据是啥时候产生的吗？如何放到数据盘吗？

可以：export TMPDIR=/root/autodl-tmp/Projects/tmp来指定生成中间文件的路径

**Comment by Tlntin** [comment]
> > 我看生成的/tmp/tmpxft_00001863_00000000-9_bf16_int4_gemm_fg_scalebias.compute_80.ptx这些中间文件，都是放在\tmp系统盘中的，大佬知道这些数据是啥时候产生的吗？如何放到数据盘吗？
> 
> 可以：export TMPDIR=/root/autodl-tmp/Projects/tmp来指定生成中间文件的路径

是的，这一步要在编译前导入。

**Comment by oreo-lp** [comment]
> 是的，这一步要在编译前导入。
请问编译的时候报这个错误：
<img width="754" alt="微信图片_20231227133731" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/59597908/d5cc50e1-6d24-4263-a997-3056d07803c1">
这是什么问题？

这是我执行的命令：

 

>export PATH=/root/miniconda3/envs/tensorrt/bin:$PATH
>export PATH=/usr/local/tensorrt/bin/:$PATH
>export LD_LIBRARY_PATH=/usr/local/tensorrt/lib/:$LD_LIBRARY_PATH
>export PATH=/root/autodl-tmp/Projects/cmake/bin:$PATH
>export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH  # libm.so.6找不到
> 
>rm -rf /root/autodl-tmp/Projects/tmp/*
>export TMPDIR=/root/autodl-tmp/Projects/tmp
>source /etc/network_turbo
> 
>export BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
>python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}

**Comment by Tlntin** [comment]
空间不足应该是，你可以看看空间变化。
