### ISSUE TITLE
summarize.py运行解答

### ISSUE THREAD

**Issue by lyc728** [Tlntin/Qwen-TensorRT-LLM#56]
你好，有关于这个分数的一个说明吗？
<img width="356" alt="企业微信截图_1703814568353" src="https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/88084847/09aa23d8-912c-4de4-8de3-9a497e9f750d">

**Comment by Tlntin** [comment]
具体指标定义可以谷歌一下或者chatgpt?大概就是生成文本和目标文本的文本相似度，只要trt-llm和hf原版差不多计算ok。
