### ISSUE TITLE
请问是否有尝试过在mpirun -n 大于1的情况下提供http服务？

### ISSUE THREAD

**Issue by xikaluo** [Tlntin/Qwen-TensorRT-LLM#59]
作者您好，请问您有尝试过根据tp_size==2时build出的engine来提供http服务吗？

我目前有一个在单卡上build出的Qwen-7B-Chat的engine和一个在两张卡上build出的Qwen-14B-Chat的engine。当我使用7B的engine，并通过mpirun -n 1 python app.py运行服务时，能够正常生成文本。但是如果使用mpirun -n 2 python app.py来运行14B的engine，则会在调用模型时卡住。

想问一下您之前是否有遇到过这类的问题？应该如何解决呢？

具体的build代码是：
```
CUDA_VISIBLE_DEVICES=0,1 python build.py --hf_model_dir ./models/qwen/Qwen-14B-Chat \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/Qwen/14B/trt_engines/fp16/2-gpu/ \
                --world_size 2 \
                --tp_size 2
```

fastapi服务代码为：
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
import uvicorn
from fastapi import Request, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from typing import *
from pydantic import BaseModel

from mpi4py import MPI

from tensorRT_generator_runner import tensorrt_generator

app = FastAPI(debug=False, version="0.0.1")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Req_ChatBook(BaseModel):
    system: Text
    history: List = []
    query: Text
    gen_args: Dict = {}
    

@app.post("/chat")
async def chat(request: Request, greq: Req_ChatBook):
    system_text = ""
    history = []
    query_text = greq.query
    gen_args = {}
    input_data_list = [{"system": system_text, "history": history, "query": query_text}]
    
    output = ""
    for x in tensorrt_generator.generate(input_data_list, gen_args):
        output = x
        print(x)
    
    return JSONResponse({"status": "ok", "response": output})

    
if __name__ == "__main__":
    if MPI.COMM_WORLD.Get_rank() == 0:
        uvicorn.run("main:app", host="0.0.0.0", port=9134, reload=False, workers=1)
    else:
        while True:
            pass
        # uvicorn.run("main:app", host="0.0.0.0", port=9135, reload=False, workers=1)
```
其中的tensorrt_generator是一个基于tensorrt_llm.runtime.ModelRunner封装的模块，通过调用ModelRunner.generate方法进行生成

**Comment by Tlntin** [comment]
其实triton可以支持你需要的多卡http，并且速度更快😅

**Comment by Reggieharden** [comment]
> 作者您好，请问您有尝试过根据tp_size==2时build出的engine来提供http服务吗？
> 
> 我目前有一个在单卡上build出的Qwen-7B-Chat的engine和一个在两张卡上build出的Qwen-14B-Chat的engine。当我使用7B的engine，并通过mpirun -n 1 python app.py运行服务时，能够正常生成文本。但是如果使用mpirun -n 2 python app.py来运行14B的engine，则会在调用模型时卡住。
> 
> 想问一下您之前是否有遇到过这类的问题？应该如何解决呢？
> 
> 具体的build代码是：
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 python build.py --hf_model_dir ./models/qwen/Qwen-14B-Chat \
>                 --dtype float16 \
>                 --remove_input_padding \
>                 --use_gpt_attention_plugin float16 \
>                 --enable_context_fmha \
>                 --use_gemm_plugin float16 \
>                 --output_dir ./tmp/Qwen/14B/trt_engines/fp16/2-gpu/ \
>                 --world_size 2 \
>                 --tp_size 2
> ```
> 
> fastapi服务代码为：
> 
> ```
> import os
> os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
> os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
> import uvicorn
> from fastapi import Request, FastAPI
> from fastapi.middleware.cors import CORSMiddleware
> from fastapi.responses import JSONResponse
> from typing import *
> from pydantic import BaseModel
> 
> from mpi4py import MPI
> 
> from tensorRT_generator_runner import tensorrt_generator
> 
> app = FastAPI(debug=False, version="0.0.1")
> app.add_middleware(
>     CORSMiddleware,
>     allow_origins=["*"],
>     allow_credentials=True,
>     allow_methods=["*"],
>     allow_headers=["*"],
> )
> 
> class Req_ChatBook(BaseModel):
>     system: Text
>     history: List = []
>     query: Text
>     gen_args: Dict = {}
>     
> 
> @app.post("/chat")
> async def chat(request: Request, greq: Req_ChatBook):
>     system_text = ""
>     history = []
>     query_text = greq.query
>     gen_args = {}
>     input_data_list = [{"system": system_text, "history": history, "query": query_text}]
>     
>     output = ""
>     for x in tensorrt_generator.generate(input_data_list, gen_args):
>         output = x
>         print(x)
>     
>     return JSONResponse({"status": "ok", "response": output})
> 
>     
> if __name__ == "__main__":
>     if MPI.COMM_WORLD.Get_rank() == 0:
>         uvicorn.run("main:app", host="0.0.0.0", port=9134, reload=False, workers=1)
>     else:
>         while True:
>             pass
>         # uvicorn.run("main:app", host="0.0.0.0", port=9135, reload=False, workers=1)
> ```
> 
> 其中的tensorrt_generator是一个基于tensorrt_llm.runtime.ModelRunner封装的模块，通过调用ModelRunner.generate方法进行生成

请问你后面有成功吗

**Comment by Reggieharden** [comment]
> 其实triton可以支持你需要的多卡http，并且速度更快😅

请问除了triton，有其他方法可以多卡启动一个http server吗

**Comment by Tlntin** [comment]
> 请问除了triton，有其他方法可以多卡启动一个http server吗

对trt-llm来说，暂时没有。

**Comment by Tlntin** [comment]
现在有了，看日志应该是适配了0.6.1，需要docker部署，然后编写yaml文件，最后启动该模型，感兴趣可以试试。
https://github.com/ray-project/ray-llm/releases/tag/v0.5.0

**Comment by ywx217** [comment]
我成功了，不过有点麻烦，需要在每一个进程都调用一次模型，不然会陷入假死状态。

示例代码：

```python
import asyncio
import time
from argparse import ArgumentParser
from typing import Dict, List, Literal, Optional, Union

import torch
import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
from mpi4py import MPI
from tensorrt_llm import mpi_rank


decoder: Optional[QWenForCausalLMGenerationSession] = None
tokenizer: Optional[AutoTokenizer] = None
generation_config: Optional[GenerationConfig] = None

app = FastAPI()


def mpi_comm():
    return MPI.COMM_WORLD


def mpi_barrier():
    mpi_comm().Barrier()


@app.post('/v1/chat/completions', response_model=ChatCompletionResponse)
async def create_chat_completion(request: ChatCompletionRequest):
    # parse request params and call LLM
    params = mpi_comm().bcast([parse_params()])
    # tensors should send to cuda AFTER bcast
    resp = call_llm(decoder, params)
    return resp


def _get_args():
    parser = ArgumentParser()
    parser.add_argument('--log_level', type=str, default='error')
    parser.add_argument(
        '-e',
        '--engine-path',
        type=str,
        default='trt_engines',
        help='TensorRT optimized engine file path, default to %(default)r',
    )
    parser.add_argument(
        '-t',
        '--tokenizer-path',
        type=str,
        default='Qwen-72B-Chat',
        help='Tokenizer path, default to %(default)r',
    )
    parser.add_argument('--api-auth', help='API authentication credentials')
    parser.add_argument('--server-port',
                        type=int,
                        default=8000,
                        help='Demo server port.')
    parser.add_argument(
        '--server-name',
        type=str,
        default='[127.0.0.1](http://127.0.0.1/)',
        help=
        'Demo server name. Default: [127.0.0.1](http://127.0.0.1/), which is only visible from the local computer.'
        ' If you want other computers to access your server, use [0.0.0.0](http://0.0.0.0/) instead.',
    )
    parser.add_argument(
        '--disable-gc',
        action='store_true',
        help='Disable GC after each response generated.',
    )
    parser.add_argument(
        "--max-beam-width",
        type=int,
        default=1,
        help='Maximum beam width for beam search. Default to 1',
    )
    parser.add_argument(
        '--timeout-keep-alive',
        type=int,
        default=5,
        help='Timeout for keep-alive connections. Default to 5',
    )
    return parser.parse_args()


async def main(args):
    global generation_config
    generation_config = GenerationConfig.from_pretrained(args.tokenizer_path)

    config = uvicorn.Config(
        app,
        host=args.server_name,
        port=args.server_port,
        workers=1,
        log_level="info",
        timeout_keep_alive=args.timeout_keep_alive,
```

**Comment by HiddenPeak** [comment]
72B编译的时候，在Linux下至少需要132GB，在docker on WSL2的话至少需要176GB，否则会被Kill。我之前只有128GB编译不走，后来调整为192GB内存后，在docker on WSL2上还是不可以，因为wsl2默认只能获得一半内存，容器初始化的时候也需要取消内存访问限制才可以。另外一个问题，你使用A6000NVLink双卡的话一定要保证NCCL能正常工作，否则可以编译但无法运行。

**Comment by UIHCRITT** [comment]
> 我成功了，不过有点麻烦，需要在每一个进程都调用一次模型，不然会陷入假死状态。
> 
> 示例代码：
> 
> ```python
> import asyncio
> import time
> from argparse import ArgumentParser
> from typing import Dict, List, Literal, Optional, Union
> 
> import torch
> import uvicorn
> from fastapi import FastAPI, HTTPException
> from fastapi.middleware.cors import CORSMiddleware
> from pydantic import BaseModel, Field
> from sse_starlette.sse import EventSourceResponse
> from starlette.middleware.base import BaseHTTPMiddleware
> from starlette.requests import Request
> from starlette.responses import Response
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from transformers.generation import GenerationConfig
> from mpi4py import MPI
> from tensorrt_llm import mpi_rank
> 
> 
> decoder: Optional[QWenForCausalLMGenerationSession] = None
> tokenizer: Optional[AutoTokenizer] = None
> generation_config: Optional[GenerationConfig] = None
> 
> app = FastAPI()
> 
> 
> def mpi_comm():
>     return MPI.COMM_WORLD
> 
> 
> def mpi_barrier():
>     mpi_comm().Barrier()
> 
> 
> @app.post('/v1/chat/completions', response_model=ChatCompletionResponse)
> async def create_chat_completion(request: ChatCompletionRequest):
>     # parse request params and call LLM
>     params = mpi_comm().bcast([parse_params()])
>     # tensors should send to cuda AFTER bcast
>     resp = call_llm(decoder, params)
>     return resp
> 
> 
> def _get_args():
>     parser = ArgumentParser()
>     parser.add_argument('--log_level', type=str, default='error')
>     parser.add_argument(
>         '-e',
>         '--engine-path',
>         type=str,
>         default='trt_engines',
>         help='TensorRT optimized engine file path, default to %(default)r',
>     )
>     parser.add_argument(
>         '-t',
>         '--tokenizer-path',
>         type=str,
>         default='Qwen-72B-Chat',
>         help='Tokenizer path, default to %(default)r',
>     )
>     parser.add_argument('--api-auth', help='API authentication credentials')
>     parser.add_argument('--server-port',
>                         type=int,
>                         default=8000,
>                         help='Demo server port.')
>     parser.add_argument(
>         '--server-name',
>         type=str,
>         default='[127.0.0.1](http://127.0.0.1/)',
>         help=
>         'Demo server name. Default: [127.0.0.1](http://127.0.0.1/), which is only visible from the local computer.'
>         ' If you want other computers to access your server, use [0.0.0.0](http://0.0.0.0/) instead.',
>     )
>     parser.add_argument(
>         '--disable-gc',
>         action='store_true',
>         help='Disable GC after each response generated.',
>     )
>     parser.add_argument(
>         "--max-beam-width",
>         type=int,
>         default=1,
>         help='Maximum beam width for beam search. Default to 1',
>     )
>     parser.add_argument(
>         '--timeout-keep-alive',
>         type=int,
>         default=5,
>         help='Timeout for keep-alive connections. Default to 5',
>     )
>     return parser.parse_args()
> 
> 
> async def main(args):
>     global generation_config
>     generation_config = GenerationConfig.from_pretrained(args.tokenizer_path)
> 
>     config = uvicorn.Config(
>         app,
>         host=args.server_name,
>         port=args.server_port,
>         workers=1,
>         log_level="info",
>         timeout_keep_alive=args.timeout_keep_alive,
>     )
>     await uvicorn.Server(config).serve()
> 
> 
> async def chat_worker(args):
>     global generation_config
>     generation_config = GenerationConfig.from_pretrained(args.tokenizer_path)
> 
>     while True:
>         params = mpi_comm().bcast([parse_params()])
>         # tensors should send to cuda AFTER bcast
>         resp = call_llm(decoder, params)
> 
> 
> def initialize(args) -> QWenForCausalLMGenerationSession:
>     global eos_pad_token_id
>     (
>         model_config, sampling_config, runtime_mapping, runtime_rank,
>         serialize_path, remove_input_padding, 
>         tokenizer, eos_token_id, pad_token_id,
>         global_max_input_length, global_max_output_length,
>     ) = get_model(args.tokenizer_path, args.engine_path, args.log_level)
>     with open(serialize_path, 'rb') as f:
>         engine_buffer = f.read()
>     decoder = QWenForCausalLMGenerationSession(
>         model_config,
>         engine_buffer,
>         runtime_mapping,
>         global_max_input_length=global_max_input_length,
>         global_max_output_length=global_max_output_length,
>     )
>     return decoder, tokenizer
> 
> 
> if __name__ == '__main__':
>     args = _get_args()
>     decoder, tokenizer = initialize(args)
>     if mpi_rank() == 0:
>         asyncio.run(main(args))
>     else:
>         asyncio.run(chat_worker(args))
> ```

can you show me the function block of  **call_llm(decoder, params)**,I get error **'coroutine' obeject is not subscriptable**  when call_llm
