### ISSUE TITLE
使用triton + inflight_batching 后吞吐反而降了

### ISSUE THREAD

**Issue by zshfeng00** [Tlntin/Qwen-TensorRT-LLM#62]
我实测来看使用triton + inflight_batching 后吞吐反而降了，fp16，8 batch，大概只有原来84%，请问下作者是否有做过triton + inflight_batching 吞吐的对比测试呢？

**Comment by zshfeng00** [comment]
更新下数据，rtiton + inflight_batching 部署的方式，随着batch的增加（大于8），吞吐是有显著提升的

**Comment by dongteng** [comment]
> 更新下结论，triton + inflight_batching 部署的方式，随着batch的增加（大于8），吞吐是有显著提升的

请问您是如何做的测试呢？
