### ISSUE TITLE
TypeError: missing a required argument: 'host_sink_token_length'

### ISSUE THREAD

**Issue by Hukongtao** [Tlntin/Qwen-TensorRT-LLM#65]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/16505966/62a14a2c-1175-49e9-b30a-d751f84b5af1)

执行build的过程报错
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/16505966/1394e568-be31-4776-b751-4375dd707bcd)

**Comment by Tlntin** [comment]
用的哪个容器？
tensorrt_llm版本？
该项目的什么分支？

**Comment by Hukongtao** [comment]
重新安装了下Qwen-TensorRT-LLM下面对应的tensorrt-llm可以跑了，之前是安装的最新的TensorRT-LLM的main分支报的错
