### ISSUE TITLE
inflight_batching

### ISSUE THREAD

**Issue by lyc728** [Tlntin/Qwen-TensorRT-LLM#66]
inflight_batching可以直接从TensorRT-LLM中操作吗？而不是通过triton的形式，还有就是[tests](https://github.com/NVIDIA/TensorRT-LLM/tree/main/tests)/[bindings](https://github.com/NVIDIA/TensorRT-LLM/tree/main/tests/bindings)
/test_gpt_manager.py这个代码是写出来进行调用吗？

**Comment by Tlntin** [comment]
1. 理论上可以，但是比较麻烦，建议triton，而且早期试过Python调用有bug（现在不知道）。
2. 这个是用来测试batch_manager代码的python调用是否ok，理论上可以基于这个魔改一个Python版的inflight-batching调用。

**Comment by lyc728** [comment]
> 1. 理论上可以，但是比较麻烦，建议triton，而且早期试过Python调用有bug（现在不知道）。
> 2. 这个是用来测试batch_manager代码的python调用是否ok，理论上可以基于这个魔改一个Python版的inflight-batching调用。

你好，我在运行[tests/bindings/test_gpt_manager.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tests/bindings/test_gpt_manager.py)时候发现import tensorrt_llm.bindings as _tb
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'这个包没有实现，我安装的tensorrt-llm 0.7.1 和0.5.0都没有解决

**Comment by Tlntin** [comment]
> > 1. 理论上可以，但是比较麻烦，建议triton，而且早期试过Python调用有bug（现在不知道）。
> > 2. 这个是用来测试batch_manager代码的python调用是否ok，理论上可以基于这个魔改一个Python版的inflight-batching调用。
> 
> 你好，我在运行[tests/bindings/test_gpt_manager.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tests/bindings/test_gpt_manager.py)时候发现import tensorrt_llm.bindings as _tb ModuleNotFoundError: No module named 'tensorrt_llm.bindings'这个包没有实现，我安装的tensorrt-llm 0.7.1 和0.5.0都没有解决

windows下面0.7.0测试了一下，没有遇到你这个问题。
我用到了下面两个文件。
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.7.0/tests/bindings/binding_test_utils.py
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.7.0/tests/bindings/test_gpt_manager.py

**Comment by lyc728** [comment]
liunx下呢？0.7.1能试下吗？

**Comment by Tlntin** [comment]
> liunx下呢？0.7.1能试下吗？

暂时没有升级0.7.1的打算，等官方triton容器更新了我才会升级哈。

**Comment by lyc728** [comment]
你好，现在我在triton环境下和在trt-llm模型下，推理结果是不一致的，
"python inflight_batcher_llm/client/inflight_batcher_llm_client.py --request-output-len 100 --tokenizer_dir /models/LLM/Translation/llms/Qwen-7B-Chat/ --text '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n写一篇具有现代化诗意的作文<|im_end|>\n<|im_start|>assistant\n' --request_id 1"
和在trt-llm下直接运行run.py，现在保证了输入的token都是一致的，请问还有什么是需要修改的吗？

**Comment by Tlntin** [comment]
> 你好，现在我在triton环境下和在trt-llm模型下，推理结果是不一致的， "python inflight_batcher_llm/client/inflight_batcher_llm_client.py --request-output-len 100 --tokenizer_dir /models/LLM/Translation/llms/Qwen-7B-Chat/ --text '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n写一篇具有现代化诗意的作文<|im_end|>\n<|im_start|>assistant\n' --request_id 1" 和在trt-llm下直接运行run.py，现在保证了输入的token都是一致的，请问还有什么是需要修改的吗？

温度，top-p/top-k/重复乘法系数等等。

**Comment by lyc728** [comment]
inflight_batcher_llm_client 好像只要温度和beam-width，top-k/p都没看到

**Comment by Tlntin** [comment]
> inflight_batcher_llm_client 好像只要温度和beam-width，top-k/p都没看到

需要的，具体都定义在triton的部署文件里面，你可以魔改一下刚刚的py文件，或者直接用http请求，加上对应的参数。
https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/triton_model_repo/ensemble/config.pbtxt

**Comment by lyc728** [comment]
你好，我添加了对应的参数后，发现结果还是没有变化
top_k = [[FLAGS.top_k]]
    top_k_data = np.array(top_k,dtype=np.uint32)
    top_p = [[FLAGS.top_p]]
    top_p_data = np.array(top_p,dtype=np.float32)
    length_penalty = [[FLAGS.length_penalty]]
    length_penalty_data = np.array(length_penalty,dtype=np.float32)
    repetition_penalty = [[FLAGS.repetition_penalty]]
    repetition_penalty_data = np.array(repetition_penalty,dtype=np.float32)
    end_id = [[151645]]
    end_id_data = np.array(top_k,dtype=np.uint32)
    pad_id= [[151645]]
    pad_id_data = np.array(pad_id,dtype=np.uint32)
    min_length = [[0]]
    min_length_data = np.array(min_length,dtype=np.uint32)

**Comment by Tlntin** [comment]
不用太过纠结，不乱码就行

**Comment by lyc728** [comment]
我现在把trt-llm和trt-llmbackend 保持在0.7.0
启动服务后，进行调用，发现报错
[TensorRT-LLM][ERROR] Encountered error for requestId 1714636916: Encountered an error in forward function: [TensorRT-LLM][ERROR] Assertion failed: input_ids: expected 2 dims, provided 1 dims (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:138)

**Comment by Tlntin** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/4607a6e3-4cb4-40dd-8050-041dce66b7b3)

**Comment by lyc728** [comment]
确实现在我基于nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3 这个镜像进行构建的，是要自己重新搭建吗？

**Comment by Tlntin** [comment]
是，需要自己编译。

**Comment by lyc728** [comment]
=> ERROR [internal] load metadata for nvcr.io/nvidia/tritonserver:23.10-py3                                                                                                                                 1.6s
------
 > [internal] load metadata for nvcr.io/nvidia/tritonserver:23.10-py3:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
我构建途中关闭了 然后重新构建就报这个错  有没有源快点的  这个好慢

**Comment by lyc728** [comment]
Input sequence:  [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264]
Got completed request
Input: Born in north-east France, Soyer trained as a
Output beam 0:  chef at the age of 15. He worked in a number of restaurants in Paris before moving to London in 1987. He has since become one of the most successful and well-known chefs in the UK, with a string of restaurants and cookbooks to his name. Soyer is known for his innovative and creative approach to cooking, and his dishes often feature a combination of traditional French techniques and modern, international influences. He has won numerous awards for his work, including the prestigious
Output sequence:  [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264, 29706, 518, 279, 4231, 315, 220, 16, 20, 13, 1260, 6439, 304, 264, 1372, 315, 15556, 304, 12095, 1573, 7218, 311, 7148, 304, 220, 16, 24, 23, 22, 13, 1260, 702, 2474, 3635, 825, 315, 279, 1429, 6849, 323, 1632, 21309, 59127, 304, 279, 6424, 11, 448, 264, 914, 315, 15556, 323, 4296, 12110, 311, 806, 829, 13, 2055, 26161, 374, 3881, 369, 806, 18199, 323, 11521, 5486, 311, 17233, 11, 323, 806, 25779, 3545, 4565, 264, 10601, 315, 8606, 8585, 12538, 323, 6481, 11, 6489, 33353, 13, 1260, 702, 2765, 12114, 22344, 369, 806, 975, 11, 2670, 279, 40285]
Exception ignored in: <function InferenceServerClient.__del__ at 0x7f6f510fb520>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 265, in close
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2101, in close
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2082, in _close
AttributeError: 'NoneType' object has no attribute 'StatusCode'

**Comment by Tlntin** [comment]
1. 正常，因为会尽量占满显存。
2. 多线程并发请求，就可以看出区别了。

**Comment by lyc728** [comment]
> Input sequence: [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264] Got completed request Input: Born in north-east France, Soyer trained as a Output beam 0: chef at the age of 15. He worked in a number of restaurants in Paris before moving to London in 1987. He has since become one of the most successful and well-known chefs in the UK, with a string of restaurants and cookbooks to his name. Soyer is known for his innovative and creative approach to cooking, and his dishes often feature a combination of traditional French techniques and modern, international influences. He has won numerous awards for his work, including the prestigious Output sequence: [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264, 29706, 518, 279, 4231, 315, 220, 16, 20, 13, 1260, 6439, 304, 264, 1372, 315, 15556, 304, 12095, 1573, 7218, 311, 7148, 304, 220, 16, 24, 23, 22, 13, 1260, 702, 2474, 3635, 825, 315, 279, 1429, 6849, 323, 1632, 21309, 59127, 304, 279, 6424, 11, 448, 264, 914, 315, 15556, 323, 4296, 12110, 311, 806, 829, 13, 2055, 26161, 374, 3881, 369, 806, 18199, 323, 11521, 5486, 311, 17233, 11, 323, 806, 25779, 3545, 4565, 264, 10601, 315, 8606, 8585, 12538, 323, 6481, 11, 6489, 33353, 13, 1260, 702, 2765, 12114, 22344, 369, 806, 975, 11, 2670, 279, 40285] Exception ignored in: <function InferenceServerClient.**del** at 0x7f6f510fb520> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in **del** File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 265, in close File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2101, in close File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2082, in _close AttributeError: 'NoneType' object has no attribute 'StatusCode'

你好 这个请求完了 然后有报错的地方，你有遇到过嘛？

**Comment by Tlntin** [comment]
> > Input sequence: [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264] Got completed request Input: Born in north-east France, Soyer trained as a Output beam 0: chef at the age of 15. He worked in a number of restaurants in Paris before moving to London in 1987. He has since become one of the most successful and well-known chefs in the UK, with a string of restaurants and cookbooks to his name. Soyer is known for his innovative and creative approach to cooking, and his dishes often feature a combination of traditional French techniques and modern, international influences. He has won numerous awards for his work, including the prestigious Output sequence: [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264, 29706, 518, 279, 4231, 315, 220, 16, 20, 13, 1260, 6439, 304, 264, 1372, 315, 15556, 304, 12095, 1573, 7218, 311, 7148, 304, 220, 16, 24, 23, 22, 13, 1260, 702, 2474, 3635, 825, 315, 279, 1429, 6849, 323, 1632, 21309, 59127, 304, 279, 6424, 11, 448, 264, 914, 315, 15556, 323, 4296, 12110, 311, 806, 829, 13, 2055, 26161, 374, 3881, 369, 806, 18199, 323, 11521, 5486, 311, 17233, 11, 323, 806, 25779, 3545, 4565, 264, 10601, 315, 8606, 8585, 12538, 323, 6481, 11, 6489, 33353, 13, 1260, 702, 2765, 12114, 22344, 369, 806, 975, 11, 2670, 279, 40285] Exception ignored in: <function InferenceServerClient.**del** at 0x7f6f510fb520> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in **del** File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 265, in close File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2101, in close File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2082, in _close AttributeError: 'NoneType' object has no attribute 'StatusCode'
> 
> 你好 这个请求完了 然后有报错的地方，你有遇到过嘛？

你这个请求有些问题，看起来不是qwen的，我没有遇到过。

**Comment by lyc728** [comment]
> > > Input sequence: [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264] Got completed request Input: Born in north-east France, Soyer trained as a Output beam 0: chef at the age of 15. He worked in a number of restaurants in Paris before moving to London in 1987. He has since become one of the most successful and well-known chefs in the UK, with a string of restaurants and cookbooks to his name. Soyer is known for his innovative and creative approach to cooking, and his dishes often feature a combination of traditional French techniques and modern, international influences. He has won numerous awards for his work, including the prestigious Output sequence: [58104, 304, 10200, 39507, 9625, 11, 2055, 26161, 16176, 438, 264, 29706, 518, 279, 4231, 315, 220, 16, 20, 13, 1260, 6439, 304, 264, 1372, 315, 15556, 304, 12095, 1573, 7218, 311, 7148, 304, 220, 16, 24, 23, 22, 13, 1260, 702, 2474, 3635, 825, 315, 279, 1429, 6849, 323, 1632, 21309, 59127, 304, 279, 6424, 11, 448, 264, 914, 315, 15556, 323, 4296, 12110, 311, 806, 829, 13, 2055, 26161, 374, 3881, 369, 806, 18199, 323, 11521, 5486, 311, 17233, 11, 323, 806, 25779, 3545, 4565, 264, 10601, 315, 8606, 8585, 12538, 323, 6481, 11, 6489, 33353, 13, 1260, 702, 2765, 12114, 22344, 369, 806, 975, 11, 2670, 279, 40285] Exception ignored in: <function InferenceServerClient.**del** at 0x7f6f510fb520> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 257, in **del** File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 265, in close File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2101, in close File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 2082, in _close AttributeError: 'NoneType' object has no attribute 'StatusCode'
> > 
> > 
> > 你好 这个请求完了 然后有报错的地方，你有遇到过嘛？
> 
> 你这个请求有些问题，看起来不是qwen的，我没有遇到过。

请求没有问题，已经输出结果了，只是结束时就报错，现在我每个请求完都有结果，然后加上下面的这行报错信息

**Comment by lyc728** [comment]
> 1. 正常，因为会尽量占满显存。
> 2. 多线程并发请求，就可以看出区别了。

你好，我这边进行多线程的并发请求，发现triton在配置中加入inflighting batch 或者V1, 耗时几乎不变
import concurrent.futures
import subprocess
import time
# 定义两个命令
import random
start = time.time()

def send_request(command):
    process = subprocess.Popen(command, shell=True)
    process.wait()
    return f"Command '{command}' executed successfully."

if __name__ == "__main__":
    texts = []
    commands = [
        "python inflight_batcher_llm/client/inflight_batcher_llm_client.py --request-output-len 100  -S --text '{}' --request-id {:d}".format(random.choice(texts), i)
        for i in range(1, 1000)
    ]

    with concurrent.futures.ThreadPoolExecutor() as executor:
        # print(commands)
        results = list(executor.map(send_request, commands))

    for result in results:
        print(result)
    print(time.time() - start)
    print("所有请求已发送并处理完成。")

**Comment by maozixi1** [comment]
> 在cmake进行编译时，会去git clone一些代码，但是我外部加了代理，为什么在编译时候还是会超时呢？如：fatal: unable to access 'https://github.com/google/googletest.git/': Failed to connect to github.com port 443 after 127379 ms: Connection timed out

请问这个问题解决了吗
