### ISSUE TITLE
Qwen-VL build.py: error: unrecognized arguments: --use_rmsnorm_plugin --use_lookup_plugin float16 --max_prompt_embedding_table_size 2048

### ISSUE THREAD

**Issue by 77h2l** [Tlntin/Qwen-TensorRT-LLM#67]
According to the readme, when run build.py in the docker as the following command:
python3 build.py  --hf_model_dir=./Qwen-VL-Chat --dtype float16 --max_batch_size 4 --remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --enable_context_fmha --use_rmsnorm_plugin --log_level error --use_lookup_plugin float16 --max_prompt_embedding_table_size 2048 --output_dir=trt_engines/Qwen-VL-7B-fp16

build.py: error: unrecognized arguments: --use_rmsnorm_plugin --use_lookup_plugin float16 --max_prompt_embedding_table_size 2048

build.py has no above agrs params actually.

**Comment by Tlntin** [comment]
Do you use example/qwen-vl/build.py?
