### ISSUE TITLE
Qwen-14B-Chat-Int4运行后预测结果不对

### ISSUE THREAD

**Issue by takemars** [Tlntin/Qwen-TensorRT-LLM#68]
在A100 80G上执行，按照要求，安装了相关的包后，按照“运行指南（int4-gptq篇）”执行第一步和第三步后，查看日志为：
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/101978375/5c79ede4-7dcf-4861-8240-7b02d2673ecc)，生成的文件如图：
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/101978375/07661da4-cb3c-46e0-a883-e62ae8d14216)
执行第三步后，正常生成的文件是这几个吗？
最后执行python3 run.py --tokenizer_dir=Qwen-14B-Chat-Int4，发现预测结果不对，本次预测结果为：
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/101978375/9c8496b3-abc5-4d67-8452-43b9a05e6bdc)
，请问如何解决这个问题？

**Comment by takemars** [comment]
补充执行第三步的指令为：python build.py --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --hf_model_dir Qwen-14B-Chat-Int4 \
                --quant_ckpt_path Qwen-14B-Chat-Int4

**Comment by Tlntin** [comment]
可以升级一下transformers版本试试。

**Comment by Tlntin** [comment]
测试了一下确实如此，可能是某次commit改挂掉了，晚点我修一下。

**Comment by Tlntin** [comment]
升级transformers版本后就可以了，该问题是optimum和transformers版本不匹配导致的，
两者都用最新版就可以解决了。
