### ISSUE TITLE
Qwen1.5 GPTQ用不了

### ISSUE THREAD

**Issue by Pevernow** [Tlntin/Qwen-TensorRT-LLM#76]
https://huggingface.co/Qwen/Qwen1.5-7B-Chat-GPTQ-Int4
用的是官方的Int4仓库，build.py报错

AttributeError: 'Qwen2Config' object has no attribute 'kv_channels'

**Comment by Tlntin** [comment]
Qwen1.5还没试过，可能要改改哈

**Comment by Tlntin** [comment]
@Pevernow Qwen1.5(Qwen2)已经支持fp16/wight only/gptq-int4，对应的summarize/api/benchmark/web_demo同步更新，相关代码存放在`examples/qwen2`目录，使用方法和之前qwen一样。
awq-int4/smooth-quant-int8还在适配中。
