### ISSUE TITLE
Qwen1.5 GPTQ-Int4 编译失败

### ISSUE THREAD

**Issue by ljhssga** [Tlntin/Qwen-TensorRT-LLM#77]
我使用的模型是Qwen-1.5-14B-Chat-GPTQ-Int4
按照流程安装了作者提供的tensorrt_llm包，使用命令
python build.py --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --hf_model_dir qwen_14b-chat-Int4 \
                --quant_ckpt_path qwen_14b-chat-Int4
报错 
FATAL：Decoding operators failed to load.This may be caused by the incompatibility between PyTorch and TensorRT-LL<.Please rebuild and install TensorRT-LLM
看起来像是torch和tensorrt-llm版本冲突的问题，我该怎么解决

**Comment by ljhssga** [comment]
补充：我使用的代码是qwen2目录下的

**Comment by ljhssga** [comment]
重试了下，问题出在import tensorrt_llm。我使用的命令：
docker pull nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3
docker tag nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3 tensorrt_llm/release
容器启动后，在容器内执行
 pip install tensorrt_llm-0.7.0-cp310-cp310-linux_x86_64.whl
安装完成后：tensorrt-llm=0.7.0、torch==2.2.1

**Comment by Tlntin** [comment]
换pytorch 2.1.0

**Comment by Tlntin** [comment]
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121

**Comment by ljhssga** [comment]
感谢，版本问题已解决。再请教一下，我在3090上跑build.py 执行过程中主机就卡死了。现想在autodl上跑，参考链接（https://www.codewithgpu.com/i/NVIDIA/TensorRT-LLM/tensorrt_llm），要运行Qwen1.5，是不是tensorrt-llm==0.6.1这个版本那就需要升级了

**Comment by Tlntin** [comment]
是的，需要升级。
升级指令参考：
- 升级pytorch（如果是2.1.0/2.1.0-dev就可以不用管）
```bash
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121
```
- 升级tensorrt-llm 
```bash
pip install tensorrt_llm==0.7.0 --extra-index-url https://pypi.nvidia.com/ --extra-index-url https://download.pytorch.org/whl/cu121
```

**Comment by Tlntin** [comment]
> 感谢，版本问题已解决。再请教一下，我在3090上跑build.py 执行过程中主机就卡死了。现想在autodl上跑

卡死可能是资源不够导致的，你可以参考readme的表格，看看你的cpu内存是否达标了。
如果用auto-dl，可能也会遇到cpu内存不够或者物理磁盘不够的问题，你可能需要租多卡来解决内存不足的问题（单卡内存也很小）。

**Comment by ljhssga** [comment]
我使用的是Qwen-1.5-14B-Chat-GPTQ-Int4，从表格看
int4 gptq (raw) | 16 | 46 | 26
-- | -- | -- | --
int4 gptq (manual) | 38 | 90 | 66
有两个raw和manual，这两个的区别是什么，并且是所有条件都要满足吗？gpu：16g 、cpu: 46g、disk: 26g

**Comment by Tlntin** [comment]
raw是官方量化好的gptq-int4，需求是比较低。
manual是你手动去将fp16量化成int4要求更高（需要将整个fp16/bf16模型加载到gpu）

**Comment by ljhssga** [comment]
> raw是官方量化好的gptq-int4，需求是比较低。 manual是你手动去将fp16量化成int4要求更高（需要将整个fp16/bf16模型加载到gpu） 上面是一个参考值，基本需要全部满足，否则可能会出现异常。

好的，我明白了。感谢！

**Comment by panjican** [comment]
你好，我在A100上编译Qwen1.5-72B-Chat-GPTQ-Int4，单卡40G，由于模型文件过大，一直报显存不足导致失败。请问要如何使用单机多卡的方式来进行编译呢~

**Comment by Tlntin** [comment]
> 你好，我在A100上编译Qwen1.5-72B-Chat-GPTQ-Int4，单卡40G，由于模型文件过大，一直报显存不足导致失败。请问要如何使用单机多卡的方式来进行编译呢~

加上`--world_size 2 --tp_size 2`这俩试试

**Comment by panjican** [comment]
> > 你好，我在A100上编译Qwen1.5-72B-Chat-GPTQ-Int4，单卡40G，由于模型文件过大，一直报显存不足导致失败。请问要如何使用单机多卡的方式来进行编译呢~
> 
> 加上`--world_size 2 --tp_size 2`这俩试试

已经加上了的，不知为何不生效TvT

**Comment by Tlntin** [comment]
> > > 你好，我在A100上编译Qwen1.5-72B-Chat-GPTQ-Int4，单卡40G，由于模型文件过大，一直报显存不足导致失败。请问要如何使用单机多卡的方式来进行编译呢~
> > 
> > 
> > 加上`--world_size 2 --tp_size 2`这俩试试
> 
> 已经加上了的，不知为何不生效TvT

weight.py
703行cuda:0换成`cuda`或者`cpu`或者`auto`试试
```python
model = AutoModelForCausalLM.from_pretrained(
                quant_ckpt_path,
                device_map="cuda:0",
                trust_remote_code=True
            ).cpu().eval()
```
目前是卡在了导入hf权重这里，单卡无法加载。
