### ISSUE TITLE
TensorRT_LLM 0.7.0 编译 Qwen-7B-Chat 模型，编译后启动API似乎无法支持并发访问API？

### ISSUE THREAD

**Issue by CedricHwong** [Tlntin/Qwen-TensorRT-LLM#79]
terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
  what():  [TensorRT-LLM][ERROR] Assertion failed: reqTypes[seqIdx] == RequestType::kGENERATION (/src/tensorrt_llm/cpp/tensorrt_llm/plugins/gptAttentionPlugin/gptAttentionPlugin.cpp:184)
1       0x7f2bc55e3225 /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0x43225) [0x7f2bc55e3225]
2       0x7f2bc566fddc /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0xcfddc) [0x7f2bc566fddc]
3       0x7f2bc566a9ed tensorrt_llm::plugins::GPTAttentionPlugin::enqueue(nvinfer1::PluginTensorDesc const*, nvinfer1::PluginTensorDesc const*, void const* const*, void* const*, void*, CUstream_st*) + 189
4       0x7f2c05739fc9 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10aefc9) [0x7f2c05739fc9]
5       0x7f2c056fce04 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1071e04) [0x7f2c056fce04]
6       0x7f2c056fe9a0 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10739a0) [0x7f2c056fe9a0]
7       0x7f2c1409dc60 /usr/local/lib/python3.10/dist-packages/tensorrt/tensorrt.so(+0x9dc60) [0x7f2c1409dc60]
8       0x7f2c14042ea3 /usr/local/lib/python3.10/dist-packages/tensorrt/tensorrt.so(+0x42ea3) [0x7f2c14042ea3]
9       0x55a939262e0e python(+0x15fe0e) [0x55a939262e0e]
10      0x55a9392595eb _PyObject_MakeTpCall + 603
11      0x55a9392717bb python(+0x16e7bb) [0x55a9392717bb]
12      0x55a9392518a2 _PyEval_EvalFrameDefault + 24914
13      0x55a93926370c _PyFunction_Vectorcall + 124
14      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
15      0x55a93926370c _PyFunction_Vectorcall + 124
16      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
17      0x55a939280552 python(+0x17d552) [0x55a939280552]
18      0x55a93924c1ef _PyEval_EvalFrameDefault + 2719
19      0x55a939280552 python(+0x17d552) [0x55a939280552]
20      0x55a93924c1ef _PyEval_EvalFrameDefault + 2719
21      0x55a939280880 python(+0x17d880) [0x55a939280880]
22      0x55a93935d13f python(+0x25a13f) [0x55a93935d13f]
23      0x55a9393fe6fb python(+0x2fb6fb) [0x55a9393fe6fb]
24      0x55a9392fea38 PyIter_Send + 120
25      0x55a93924ded6 _PyEval_EvalFrameDefault + 10118
26      0x55a939280880 python(+0x17d880) [0x55a939280880]
27      0x55a93924ded6 _PyEval_EvalFrameDefault + 10118
28      0x55a939280880 python(+0x17d880) [0x55a939280880]
29      0x7f2d68cf128e /usr/lib/python3.10/lib-dynload/_asyncio.cpython-310-x86_64-linux-gnu.so(+0x928e) [0x7f2d68cf128e]
30      0x7f2d68cf10a4 /usr/lib/python3.10/lib-dynload/_asyncio.cpython-310-x86_64-linux-gnu.so(+0x90a4) [0x7f2d68cf10a4]
31      0x55a9392595eb _PyObject_MakeTpCall + 603
32      0x55a9393b82a2 python(+0x2b52a2) [0x55a9393b82a2]
33      0x55a93925650b python(+0x15350b) [0x55a93925650b]
34      0x55a93924e2c1 _PyEval_EvalFrameDefault + 11121
35      0x55a93926370c _PyFunction_Vectorcall + 124
36      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
37      0x55a93926370c _PyFunction_Vectorcall + 124
38      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
39      0x55a93926370c _PyFunction_Vectorcall + 124
40      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
41      0x55a93926370c _PyFunction_Vectorcall + 124
42      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
43      0x55a93926370c _PyFunction_Vectorcall + 124
44      0x55a9392518a2 _PyEval_EvalFrameDefault + 24914
45      0x55a93926370c _PyFunction_Vectorcall + 124
46      0x55a93924bf52 _PyEval_EvalFrameDefault + 2050
47      0x55a93926370c _PyFunction_Vectorcall + 124
48      0x55a93924d0d1 _PyEval_EvalFrameDefault + 6529
49      0x55a93933ce56 python(+0x239e56) [0x55a93933ce56]
50      0x55a93933ccf6 PyEval_EvalCode + 134
51      0x55a9393677d8 python(+0x2647d8) [0x55a9393677d8]
52      0x55a9393610bb python(+0x25e0bb) [0x55a9393610bb]
53      0x55a939367525 python(+0x264525) [0x55a939367525]
54      0x55a939366a08 _PyRun_SimpleFileObject + 424
55      0x55a939366653 _PyRun_AnyFileObject + 67
56      0x55a93935941e Py_RunMain + 702
57      0x55a93932fcad Py_BytesMain + 45
58      0x7f2d68fe5d90 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f2d68fe5d90]
59      0x7f2d68fe5e40 __libc_start_main + 128
60      0x55a93932fba5 _start + 37
[ba05475731f2:00438] *** Process received signal ***
[ba05475731f2:00438] Signal: Aborted (6)
[ba05475731f2:00438] Signal code:  (-6)
[ba05475731f2:00438] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f2d68ffe520]
[ba05475731f2:00438] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f2d69052a7c]
[ba05475731f2:00438] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f2d68ffe476]
[ba05475731f2:00438] [ 3] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f2d68fe47f3]
[ba05475731f2:00438] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2b9e)[0x7f2c93a76b9e]
[ba05475731f2:00438] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae20c)[0x7f2c93a8220c]
[ba05475731f2:00438] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xad1e9)[0x7f2c93a811e9]
[ba05475731f2:00438] [ 7] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x99)[0x7f2c93a81959]
[ba05475731f2:00438] [ 8] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(+0x16884)[0x7f2d67ab9884]
[ba05475731f2:00438] [ 9] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x12d)[0x7f2d67aba2dd]
[ba05475731f2:00438] [10] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0xcff22)[0x7f2bc566ff22]
[ba05475731f2:00438] [11] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(_ZN12tensorrt_llm7plugins18GPTAttentionPlugin7enqueueEPKN8nvinfer116PluginTensorDescES5_PKPKvPKPvSA_P11CUstream_st+0xbd)[0x7f2bc566a9ed]
[ba05475731f2:00438] [12] /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10aefc9)[0x7f2c05739fc9]
[ba05475731f2:00438] [13] /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1071e04)[0x7f2c056fce04]
[ba05475731f2:00438] [14] /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10739a0)[0x7f2c056fe9a0]
[ba05475731f2:00438] [15] /usr/local/lib/python3.10/dist-packages/tensorrt/tensorrt.so(+0x9dc60)[0x7f2c1409dc60]
[ba05475731f2:00438] [16] /usr/local/lib/python3.10/dist-packages/tensorrt/tensorrt.so(+0x42ea3)[0x7f2c14042ea3]
[ba05475731f2:00438] [17] python(+0x15fe0e)[0x55a939262e0e]
[ba05475731f2:00438] [18] python(_PyObject_MakeTpCall+0x25b)[0x55a9392595eb]
[ba05475731f2:00438] [19] python(+0x16e7bb)[0x55a9392717bb]
[ba05475731f2:00438] [20] python(_PyEval_EvalFrameDefault+0x6152)[0x55a9392518a2]
[ba05475731f2:00438] [21] python(_PyFunction_Vectorcall+0x7c)[0x55a93926370c]
[ba05475731f2:00438] [22] python(_PyEval_EvalFrameDefault+0x802)[0x55a93924bf52]
[ba05475731f2:00438] [23] python(_PyFunction_Vectorcall+0x7c)[0x55a93926370c]
[ba05475731f2:00438] [24] python(_PyEval_EvalFrameDefault+0x802)[0x55a93924bf52]
[ba05475731f2:00438] [25] python(+0x17d552)[0x55a939280552]
[ba05475731f2:00438] [26] python(_PyEval_EvalFrameDefault+0xa9f)[0x55a93924c1ef]
[ba05475731f2:00438] [27] python(+0x17d552)[0x55a939280552]
[ba05475731f2:00438] [28] python(_PyEval_EvalFrameDefault+0xa9f)[0x55a93924c1ef]
[ba05475731f2:00438] [29] python(+0x17d880)[0x55a939280880]

**Comment by Tlntin** [comment]
trtion部署？

**Comment by CedricHwong** [comment]
解决了，不是trt这边的原因
