### ISSUE TITLE
有人能共享Build好的qwen或qwen1.5 int4的trt_engine（4gpu）文件吗？

### ISSUE THREAD

**Issue by zhangjiekui** [Tlntin/Qwen-TensorRT-LLM#85]
【HELP】我有4*4090 GPU,但是CPU内存不足以支持Build qwen或qwen1.5 gptq int4的模型，希望有好心人能够共享。
【BUG？】或者能帮忙解决build过程中的OOM错误，在parallel_build时，模型只往GPU 0 上装载

**Comment by zhangjiekui** [comment]
通过nvidia-smi -l 命令发现，模型只往GPU 0 上装载

具体build命令为：
CUDA_MODULE_LOADING=LAZY python build.py --hf_model_dir /app/tensorrt_llm/examples/qwen2/qwen1.5_72b_chat_int4                  --parallel_build                 --quant_ckpt_path /app/tensorrt_llm/examples/qwen2/qwen1.5_72b_chat_int4                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --enable_context_fmha                 --use_gemm_plugin float16                 --use_weight_only                 --weight_only_precision int4_gptq                 --per_group                 --world_size 4                 --tp_size 4 --pp_size 1                 --gpus_per_node 4                --output_dir /app/tensorrt_llm/examples/qwen2/qwen1.5_72b_chat_int4/trt_engines/int4-gptq/4-gpu

**Comment by zhangjiekui** [comment]
是我做的不对吗？请帮忙看看

**Comment by zhangjiekui** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/33198334/7f003efb-812f-4541-969a-9ea09df1a21c)

**Comment by zhangjiekui** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/33198334/c756033e-8769-450e-a9c8-be8e010a4ad9)

**Comment by zhangjiekui** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/33198334/956ed5bc-4849-4d27-a51f-cc1be8e264ff)

**Comment by zhangjiekui** [comment]
以上三张图分别是OOM前、中间、开始装载模型时的GPU占用情况

**Comment by Tlntin** [comment]
https://github.com/Tlntin/Qwen-TensorRT-LLM/issues/77
参考这个改改让它支持多卡，忘记修了😅。

**Comment by zhangjiekui** [comment]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/33198334/b546428f-7d45-41cb-830e-0d0be56a2a3d)
这样才行，否则显存还是会爆炸

**Comment by liyunhan** [comment]
大佬，如果我下载hf官网提供的qwen1.5-72b-chat-gptq-int4模型，是不是在trtllm-backend编译的时候就不需要添加--use_weight_only等命令，只需要设置输入长度、模型编译前后的路径就好了？

**Comment by Tlntin** [comment]
需要，参考readme下面这个命令。
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/dc36a5bc-4b14-4b98-a7da-c2717170cd0c)

**Comment by liyunhan** [comment]
> 需要，参考readme下面这个命令。 ![image](https://private-user-images.githubusercontent.com/28218658/312667368-dc36a5bc-4b14-4b98-a7da-c2717170cd0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODA0OTcsIm5iZiI6MTcxMDM4MDE5NywicGF0aCI6Ii8yODIxODY1OC8zMTI2NjczNjgtZGMzNmE1YmMtNGIxNC00Yjk4LWE3ZGEtYzI3MTcxNzBjZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAxMzYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjQwNzQ3MzlhY2YyNzg3YzMyNDYwMGFhNjVmNGIxNTViNTJiOTlhOGE5NzQ4OWI5MWU4MmM2NTc4Y2IwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8FSNpUCt4Lr4dEQn4V1Va1_ydrmtbWwp8ubtz20GOUw)

谢谢大佬！

**Comment by liyunhan** [comment]
> 需要，参考readme下面这个命令。 ![image](https://private-user-images.githubusercontent.com/28218658/312667368-dc36a5bc-4b14-4b98-a7da-c2717170cd0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODQ2MzIsIm5iZiI6MTcxMDM4NDMzMiwicGF0aCI6Ii8yODIxODY1OC8zMTI2NjczNjgtZGMzNmE1YmMtNGIxNC00Yjk4LWE3ZGEtYzI3MTcxNzBjZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyNDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NWNhY2I5MjQ2OGM5NTViODg3NmVlMzkwMjIzMjgwMWYyODVkZmQ3MzMyMDllZWExOThhMTNjZWI2ZGUzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1C_HhKeoy_ChreNK8Iw2H4a_ZRseiRtZY8x-AYlN9k)

大佬我还有疑问求解，我在tensorrt-llm的github看到他最新的v8.0版本是支持qwen1.5的一系列新特性，在环境要求上写了这么一条：“TensorRT-LLM requires TensorRT 9.2 and 23.12 containers.”。
这里23.12 container我理解是指triton server的container版本，但是我看nvidia官网显示这个版本的容器tensorrt是8.6.1.6版本，这是什么情况？
