### ISSUE TITLE
请问目前的Qwen-VL实现方式，是否仅支持输入单张图片，且图片必须在输入的开头？

### ISSUE THREAD

**Issue by xikaluo** [Tlntin/Qwen-TensorRT-LLM#90]
您好，谢谢您提供的qwen-vl的实现代码。我看您在代码里是通过p-tuning来将图片向量插入输入中，这样是否就意味着在用户的输入文本里，图片必须处在最开始的位置？
我自己测试时发现，如果在https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen-vl/run.py#L649 之后将图片和文本的顺序替换，那模型就只会根据图片进行回答，不再能响应输入文本里的要求：

修改后的run.py的__main__方法为：
```
if __name__ == '__main__':
    args = parse_arguments()
    vit = Vit(args.vit_engine_dir, args.log_level)
    image_embeds = vit.run(args.input_dir)
    qinfer = QWenInfer(args.tokenizer_dir, args.qwen_engine_dir, args.log_level,
                       args.output_csv, args.output_npy, args.num_beams)
    qinfer.qwen_model_init()
    if args.images_path is None:
        content_list = [{"text": args.input_text}]
    else:
        content_list = args.images_path + [{"text": args.input_text}]
    content_list = [{"text": args.input_text}] + args.images_path  # 添加了这一行代码，交换顺序
    query = qinfer.tokenizer.from_list_format(content_list)
    qinfer.qwen_infer(
        input_text=query,
        max_new_tokens=args.max_new_tokens,
        input_vit=image_embeds,
    )
```

run.py的调用方法为：
```
python run.py \
    --vit_engine_dir ./plan/ \
    --tokenizer_dir ./models/Qwen-VL-Chat \
    --qwen_engine_dir ./trt_engines/Qwen-VL-7B-fp16/ \
    --input_text 这张图里有二十个人，对吧？
```

终端输出为：
```
[03/15/2024-13:54:14] [TRT-LLM] [I] Loading engine from ./plan/visual_encoder/visual_encoder_fp16.plan
[03/15/2024-13:54:17] [TRT-LLM] [I] Creating session from engine ./plan/visual_encoder/visual_encoder_fp16.plan
[03/15/2024-13:54:17] [TRT] [I] Loaded engine size: 7396 MiB
[03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +7389, now: CPU 0, GPU 7389 (MiB)
[03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +788, now: CPU 0, GPU 8177 (MiB)
[03/15/2024-13:54:19] [TRT] [W] Using default stream in enqueue()/enqueueV2()/enqueueV3() may lead to performance issues due to additional cudaDeviceSynchronize() calls by TensorRT to ensure correct synchronizations. Please use non-default stream instead.
[03/15/2024-13:54:19] [TRT-LLM] [I] TensorRT-LLM ViT latency: 0.014642953872680664 sec 
Loading engine from ./trt_engines/Qwen-VL-7B-fp16/qwen_float16_tp1_rank0.engine
[03/15/2024-13:54:26] [TRT] [I] Loaded engine size: 14728 MiB
[03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15031, GPU 27862 (MiB)
[03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 15032, GPU 27872 (MiB)
[03/15/2024-13:54:27] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14727, now: CPU 0, GPU 22904 (MiB)
[03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15052, GPU 28042 (MiB)
[03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 15052, GPU 28050 (MiB)
[03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
[03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15054, GPU 28058 (MiB)
[03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 15054, GPU 28068 (MiB)
[03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
Input: "[{'text': '这张图里有二十个人，对吧？'}, {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'}]"


Output: "Received."


```

另外我发现按照这种方式，system_text的改动也无法影响模型输出了？

希望能得到您的解答，谢谢～

**Comment by Tlntin** [comment]
> 是否仅单张图片?

 一次应该是一张，不过多轮对话的话，算起来就是多张了，具体可以看api.py和web_demo的实现。
> 图片是否必须在输入的开头?

是的，必须。先给图，才能讨论图。而不是先讨论，再给图，逻辑没办法实现。

**Comment by yzq1990** [comment]
> 您好，谢谢您提供的qwen-vl的实现代码。我看您在代码里是通过p-tuning来将图片向量插入输入中，这样是否就意味着在用户的输入文本里，图片必须处在最开始的位置？ 我自己测试时发现，如果在https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen-vl/run.py#L649 之后将图片和文本的顺序替换，那模型就只会根据图片进行回答，不再能响应输入文本里的要求：
> 
> 修改后的run.py的__main__方法为：
> 
> ```
> if __name__ == '__main__':
>     args = parse_arguments()
>     vit = Vit(args.vit_engine_dir, args.log_level)
>     image_embeds = vit.run(args.input_dir)
>     qinfer = QWenInfer(args.tokenizer_dir, args.qwen_engine_dir, args.log_level,
>                        args.output_csv, args.output_npy, args.num_beams)
>     qinfer.qwen_model_init()
>     if args.images_path is None:
>         content_list = [{"text": args.input_text}]
>     else:
>         content_list = args.images_path + [{"text": args.input_text}]
>     content_list = [{"text": args.input_text}] + args.images_path  # 添加了这一行代码，交换顺序
>     query = qinfer.tokenizer.from_list_format(content_list)
>     qinfer.qwen_infer(
>         input_text=query,
>         max_new_tokens=args.max_new_tokens,
>         input_vit=image_embeds,
>     )
> ```
> 
> run.py的调用方法为：
> 
> ```
> python run.py \
>     --vit_engine_dir ./plan/ \
>     --tokenizer_dir ./models/Qwen-VL-Chat \
>     --qwen_engine_dir ./trt_engines/Qwen-VL-7B-fp16/ \
>     --input_text 这张图里有二十个人，对吧？
> ```
> 
> 终端输出为：
> 
> ```
> [03/15/2024-13:54:14] [TRT-LLM] [I] Loading engine from ./plan/visual_encoder/visual_encoder_fp16.plan
> [03/15/2024-13:54:17] [TRT-LLM] [I] Creating session from engine ./plan/visual_encoder/visual_encoder_fp16.plan
> [03/15/2024-13:54:17] [TRT] [I] Loaded engine size: 7396 MiB
> [03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +7389, now: CPU 0, GPU 7389 (MiB)
> [03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +788, now: CPU 0, GPU 8177 (MiB)
> [03/15/2024-13:54:19] [TRT] [W] Using default stream in enqueue()/enqueueV2()/enqueueV3() may lead to performance issues due to additional cudaDeviceSynchronize() calls by TensorRT to ensure correct synchronizations. Please use non-default stream instead.
> [03/15/2024-13:54:19] [TRT-LLM] [I] TensorRT-LLM ViT latency: 0.014642953872680664 sec 
> Loading engine from ./trt_engines/Qwen-VL-7B-fp16/qwen_float16_tp1_rank0.engine
> [03/15/2024-13:54:26] [TRT] [I] Loaded engine size: 14728 MiB
> [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15031, GPU 27862 (MiB)
> [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 15032, GPU 27872 (MiB)
> [03/15/2024-13:54:27] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14727, now: CPU 0, GPU 22904 (MiB)
> [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15052, GPU 28042 (MiB)
> [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 15052, GPU 28050 (MiB)
> [03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
> [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15054, GPU 28058 (MiB)
> [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 15054, GPU 28068 (MiB)
> [03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
> Input: "[{'text': '这张图里有二十个人，对吧？'}, {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'}]"
> 
> 
> Output: "Received."
> ```
> 
> 另外我发现按照这种方式，system_text的改动也无法影响模型输出了？
> 
> 希望能得到您的解答，谢谢～

Can you provide the onnx format model of qwen-VL-Chat? I encounter some peoblem during the transmit process.

**Comment by Tlntin** [comment]
> > 您好，谢谢您提供的qwen-vl的实现代码。我看您在代码里是通过p-tuning来将图片向量插入输入中，这样是否就意味着在用户的输入文本里，图片必须处在最开始的位置？ 我自己测试时发现，如果在https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen-vl/run.py#L649 之后将图片和文本的顺序替换，那模型就只会根据图片进行回答，不再能响应输入文本里的要求：
> > 修改后的run.py的__main__方法为：
> > ```
> > if __name__ == '__main__':
> >     args = parse_arguments()
> >     vit = Vit(args.vit_engine_dir, args.log_level)
> >     image_embeds = vit.run(args.input_dir)
> >     qinfer = QWenInfer(args.tokenizer_dir, args.qwen_engine_dir, args.log_level,
> >                        args.output_csv, args.output_npy, args.num_beams)
> >     qinfer.qwen_model_init()
> >     if args.images_path is None:
> >         content_list = [{"text": args.input_text}]
> >     else:
> >         content_list = args.images_path + [{"text": args.input_text}]
> >     content_list = [{"text": args.input_text}] + args.images_path  # 添加了这一行代码，交换顺序
> >     query = qinfer.tokenizer.from_list_format(content_list)
> >     qinfer.qwen_infer(
> >         input_text=query,
> >         max_new_tokens=args.max_new_tokens,
> >         input_vit=image_embeds,
> >     )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > run.py的调用方法为：
> > ```
> > python run.py \
> >     --vit_engine_dir ./plan/ \
> >     --tokenizer_dir ./models/Qwen-VL-Chat \
> >     --qwen_engine_dir ./trt_engines/Qwen-VL-7B-fp16/ \
> >     --input_text 这张图里有二十个人，对吧？
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 终端输出为：
> > ```
> > [03/15/2024-13:54:14] [TRT-LLM] [I] Loading engine from ./plan/visual_encoder/visual_encoder_fp16.plan
> > [03/15/2024-13:54:17] [TRT-LLM] [I] Creating session from engine ./plan/visual_encoder/visual_encoder_fp16.plan
> > [03/15/2024-13:54:17] [TRT] [I] Loaded engine size: 7396 MiB
> > [03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +7389, now: CPU 0, GPU 7389 (MiB)
> > [03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +788, now: CPU 0, GPU 8177 (MiB)
> > [03/15/2024-13:54:19] [TRT] [W] Using default stream in enqueue()/enqueueV2()/enqueueV3() may lead to performance issues due to additional cudaDeviceSynchronize() calls by TensorRT to ensure correct synchronizations. Please use non-default stream instead.
> > [03/15/2024-13:54:19] [TRT-LLM] [I] TensorRT-LLM ViT latency: 0.014642953872680664 sec 
> > Loading engine from ./trt_engines/Qwen-VL-7B-fp16/qwen_float16_tp1_rank0.engine
> > [03/15/2024-13:54:26] [TRT] [I] Loaded engine size: 14728 MiB
> > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15031, GPU 27862 (MiB)
> > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 15032, GPU 27872 (MiB)
> > [03/15/2024-13:54:27] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14727, now: CPU 0, GPU 22904 (MiB)
> > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15052, GPU 28042 (MiB)
> > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 15052, GPU 28050 (MiB)
> > [03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
> > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15054, GPU 28058 (MiB)
> > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 15054, GPU 28068 (MiB)
> > [03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
> > Input: "[{'text': '这张图里有二十个人，对吧？'}, {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'}]"
> > 
> > 
> > Output: "Received."
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外我发现按照这种方式，system_text的改动也无法影响模型输出了？
> > 希望能得到您的解答，谢谢～
> 
> Can you provide the onnx format model of qwen-VL-Chat? I encounter some peoblem during the transmit process.

![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/28218658/74614d89-f9d9-4203-9bc5-b74f11dd3402)

**Comment by yzq1990** [comment]
Hi, I met the problem during the transmit process.

**Comment by yzq1990** [comment]
> > > 您好，谢谢您提供的qwen-vl的实现代码。我看您在代码里是通过p-tuning来将图片向量插入输入中，这样是否就意味着在用户的输入文本里，图片必须处在最开始的位置？ 我自己测试时发现，如果在https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/examples/qwen-vl/run.py#L649 之后将图片和文本的顺序替换，那模型就只会根据图片进行回答，不再能响应输入文本里的要求：
> > > 修改后的run.py的__main__方法为：
> > > ```
> > > if __name__ == '__main__':
> > >     args = parse_arguments()
> > >     vit = Vit(args.vit_engine_dir, args.log_level)
> > >     image_embeds = vit.run(args.input_dir)
> > >     qinfer = QWenInfer(args.tokenizer_dir, args.qwen_engine_dir, args.log_level,
> > >                        args.output_csv, args.output_npy, args.num_beams)
> > >     qinfer.qwen_model_init()
> > >     if args.images_path is None:
> > >         content_list = [{"text": args.input_text}]
> > >     else:
> > >         content_list = args.images_path + [{"text": args.input_text}]
> > >     content_list = [{"text": args.input_text}] + args.images_path  # 添加了这一行代码，交换顺序
> > >     query = qinfer.tokenizer.from_list_format(content_list)
> > >     qinfer.qwen_infer(
> > >         input_text=query,
> > >         max_new_tokens=args.max_new_tokens,
> > >         input_vit=image_embeds,
> > >     )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > run.py的调用方法为：
> > > ```
> > > python run.py \
> > >     --vit_engine_dir ./plan/ \
> > >     --tokenizer_dir ./models/Qwen-VL-Chat \
> > >     --qwen_engine_dir ./trt_engines/Qwen-VL-7B-fp16/ \
> > >     --input_text 这张图里有二十个人，对吧？
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 终端输出为：
> > > ```
> > > [03/15/2024-13:54:14] [TRT-LLM] [I] Loading engine from ./plan/visual_encoder/visual_encoder_fp16.plan
> > > [03/15/2024-13:54:17] [TRT-LLM] [I] Creating session from engine ./plan/visual_encoder/visual_encoder_fp16.plan
> > > [03/15/2024-13:54:17] [TRT] [I] Loaded engine size: 7396 MiB
> > > [03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +7389, now: CPU 0, GPU 7389 (MiB)
> > > [03/15/2024-13:54:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +788, now: CPU 0, GPU 8177 (MiB)
> > > [03/15/2024-13:54:19] [TRT] [W] Using default stream in enqueue()/enqueueV2()/enqueueV3() may lead to performance issues due to additional cudaDeviceSynchronize() calls by TensorRT to ensure correct synchronizations. Please use non-default stream instead.
> > > [03/15/2024-13:54:19] [TRT-LLM] [I] TensorRT-LLM ViT latency: 0.014642953872680664 sec 
> > > Loading engine from ./trt_engines/Qwen-VL-7B-fp16/qwen_float16_tp1_rank0.engine
> > > [03/15/2024-13:54:26] [TRT] [I] Loaded engine size: 14728 MiB
> > > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15031, GPU 27862 (MiB)
> > > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 15032, GPU 27872 (MiB)
> > > [03/15/2024-13:54:27] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> > > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14727, now: CPU 0, GPU 22904 (MiB)
> > > [03/15/2024-13:54:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15052, GPU 28042 (MiB)
> > > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 15052, GPU 28050 (MiB)
> > > [03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> > > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
> > > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 15054, GPU 28058 (MiB)
> > > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 15054, GPU 28068 (MiB)
> > > [03/15/2024-13:54:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
> > > [03/15/2024-13:54:28] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 22904 (MiB)
> > > Input: "[{'text': '这张图里有二十个人，对吧？'}, {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'}]"
> > > 
> > > 
> > > Output: "Received."
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 另外我发现按照这种方式，system_text的改动也无法影响模型输出了？
> > > 希望能得到您的解答，谢谢～
> > 
> > 
> > Can you provide the onnx format model of qwen-VL-Chat? I encounter some peoblem during the transmit process.
> 
> ![image](https://private-user-images.githubusercontent.com/28218658/340987554-74614d89-f9d9-4203-9bc5-b74f11dd3402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODU1MTMsIm5iZiI6MTcxODc4NTIxMywicGF0aCI6Ii8yODIxODY1OC8zNDA5ODc1NTQtNzQ2MTRkODktZjlkOS00MjAzLTliYzUtYjc0ZjExZGQzNDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MGIyYTgwNWJiZDliOTc1NDZlYTQyZTdlNzlhZWEwNDk1MDAyNzgxOTIxOTIzMTU3ODNkZGU2Y2Q2YTk1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82OFfc3mo9osK3oyQ-AszIOqiUuEUhQsz3BaFPnr8qg)

Hi, I met the problem during the transmit process.
'''
cmd1:
python vit_onnx_trt.py --pretrained_model_path ./Qwen-VL-Chat
'''
'''
cmd2:
python3 build.py
--hf_model_dir=./Qwen-VL-Chat-Int4
--quant_ckpt_path=./Qwen-VL-Chat-Int4
--dtype float16 --max_batch_size 4
--remove_input_padding
--use_gpt_attention_plugin float16
--use_gemm_plugin float16 --enable_context_fmha
--use_rmsnorm_plugin --log_level error
--use_lookup_plugin float16
--max_prompt_embedding_table_size 2048
--use_weight_only
--weight_only_precision int4_gptq
--per_group
--output_dir=trt_engines/Qwen-VL-7B-int4-gptq
'''
'''
cmd3:
python run.py
--tokenizer_dir=./Qwen-VL-Chat-Int4
--qwen_engine_dir=trt_engines/Qwen-VL-7B-int4-gptq
--vit_engine_dir=./plan/
'''
I can't find the 'plan' filefold when finished cmd1.
So I can't run the cmd3.

**Comment by Tlntin** [comment]
@yzq1990 i think you should use TensorRT-LLM == 0.7.0

**Comment by yzq1990** [comment]
> @yzq1990 i think you should use TensorRT-LLM == 0.7.0

yes, i used TensorRT-LLM == 0.7.0, and still run with the problem.
