### ISSUE TITLE
Triton 和 Langchain部署问题

### ISSUE THREAD

**Issue by plt12138** [Tlntin/Qwen-TensorRT-LLM#95]
首先感谢，跟着你的文章和项目学习的TensorRT-LLM，目前能够通过curl 和 tensorrllm_backend 交互问答。
我看这个项目支持Langchain部署 [docs/trt_llm_deploy_langchain.md](https://github.com/Tlntin/Qwen-TensorRT-LLM/blob/main/docs/trt_llm_deploy_langchain.md)，是自行搭建的fastapi来实现openai请求。想请问 Triton 的 tensorrllm_backend 是否能和 Langchain 或 langflow之类交互？

**Comment by Tlntin** [comment]
你可以自己用fastapi搭建一个，然后接收用户请求，再发给triton，再包装triton请求，再发给用户？

**Comment by Tlntin** [comment]
如果你会一点点rust，可以直接用这个项目，启动它的rust服务就可以做到。
https://github.com/npuichigo/openai_trtllm/tree/main

**Comment by plt12138** [comment]
> 你可以自己用fastapi搭建一个，然后接收用户请求，再发给triton，再包装triton请求，再发给用户？

我理解这样肯定可以实现，但我更想了解 tensorrllm_backend 是用于什么场景呢？启动它时可以指定支持多卡、多并发，但没提供对应的api？
因为我刚刚接触LLM，接触到的可能全都围绕着langchian…… 之前用fastchat部署模型，是直接提供openai的api，所以改成用这个有点迷茫。

**Comment by Tlntin** [comment]
> > 你可以自己用fastapi搭建一个，然后接收用户请求，再发给triton，再包装triton请求，再发给用户？
> 
> 我理解这样肯定可以实现，但我更想了解 tensorrllm_backend 是用于什么场景呢？启动它时可以指定支持多卡、多并发，但没提供对应的api？ 因为我刚刚接触LLM，接触到的可能全都围绕着langchian…… 之前用fastchat部署模型，是直接提供openai的api，所以改成用这个有点迷茫。

可以看成是一个高性能的Nginx，速度和并发都很高，triton算是企业级部署常用工具了。
`，但没提供对应的api？`这个说法不太对，它有自己的api，只不过格式不是遵循openai格式而已，就像苹果也不会去兼容安卓的安装包一样。

**Comment by plt12138** [comment]
理解了，谢谢！
