### ISSUE TITLE
编译tritonserver 镜像 失败

### ISSUE THREAD

**Issue by maozixi1** [Tlntin/Qwen-TensorRT-LLM#96]
![image](https://github.com/Tlntin/Qwen-TensorRT-LLM/assets/139109502/a5cae238-6a6d-4098-864c-465a1024c02b)

**Comment by maozixi1** [comment]
> 换0.8.0,目前在当前项目的main分支，triton这块目前测试是ok的，不需要自己编译了。

谢谢，请问部署triton时如何设置多gpu或者指定显卡

**Comment by Tlntin** [comment]
编译的时候指定多卡`--world_size 2 --tp_size 2`，部署的时候配置文件有一个指定gpu的参数。

**Comment by maozixi1** [comment]
> 编译的时候指定多卡`--world_size 2 --tp_size 2`，部署的时候配置文件有一个指定gpu的参数。

好的，谢谢
